// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package mix

// Generated from OpenAPI doc version 1.0.0 and generator version 2.816.0

import (
	"github.com/recreate-run/mix-go-sdk/internal/config"
	"github.com/recreate-run/mix-go-sdk/internal/hooks"
	"github.com/recreate-run/mix-go-sdk/retry"
	"net/http"
	"time"
)

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

// Mix REST API: REST API for the Mix application - session management, messaging, and system operations
type Mix struct {
	SDKVersion     string
	Authentication *Authentication
	System         *System
	Messages       *Messages
	Notifications  *Notifications
	Permissions    *Permissions
	Preferences    *Preferences
	Sessions       *Sessions
	Files          *Files
	Tools          *Tools
	Health         *Health
	Internal       *Internal
	Streaming      *Streaming

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*Mix)

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *Mix) {
		sdk.sdkConfiguration.Client = client
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *Mix) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *Mix) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided serverURL and options
func New(serverURL string, opts ...SDKOption) *Mix {
	sdk := &Mix{
		SDKVersion: "0.2.1",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent: "speakeasy-sdk/go 0.2.1 2.816.0 1.0.0 github.com/recreate-run/mix-go-sdk",
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	sdk.sdkConfiguration.ServerURL = serverURL

	sdk.sdkConfiguration = sdk.hooks.SDKInit(sdk.sdkConfiguration)

	sdk.Authentication = newAuthentication(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.System = newSystem(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Messages = newMessages(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Notifications = newNotifications(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Permissions = newPermissions(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Preferences = newPreferences(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Sessions = newSessions(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Files = newFiles(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Tools = newTools(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Health = newHealth(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Internal = newInternal(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Streaming = newStreaming(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
