// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/recreate-run/mix-go-sdk/internal/utils"
	"github.com/recreate-run/mix-go-sdk/models/components"
)

// PromptMode - Custom prompt handling mode:
// - 'default': Use base system prompt only (customSystemPrompt ignored)
// - 'append': Append customSystemPrompt to base system prompt (50KB limit)
// - 'replace': Replace base system prompt with customSystemPrompt (100KB limit)
type PromptMode string

const (
	PromptModeDefault PromptMode = "default"
	PromptModeAppend  PromptMode = "append"
	PromptModeReplace PromptMode = "replace"
)

func (e PromptMode) ToPointer() *PromptMode {
	return &e
}
func (e *PromptMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "default":
		fallthrough
	case "append":
		fallthrough
	case "replace":
		*e = PromptMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PromptMode: %v", v)
	}
}

// SessionType - Session type. API can only create 'main' sessions. Subagent sessions are created automatically by the task delegation system.
type SessionType string

const (
	SessionTypeMain SessionType = "main"
)

func (e SessionType) ToPointer() *SessionType {
	return &e
}
func (e *SessionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "main":
		*e = SessionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SessionType: %v", v)
	}
}

type CreateSessionRequest struct {
	// Session-level callbacks that execute after tool completion. Environment variables available: CALLBACK_TOOL_RESULT, CALLBACK_TOOL_NAME, CALLBACK_TOOL_ID, CALLBACK_SESSION_ID
	Callbacks []components.Callback `json:"callbacks,omitempty"`
	// Custom system prompt content. Size limits apply based on promptMode: 100KB (102,400 bytes) for replace mode, 50KB (51,200 bytes) for append mode. Ignored in default mode. Supports environment variable substitution with $<variable> syntax.
	CustomSystemPrompt *string `json:"customSystemPrompt,omitempty"`
	// Custom prompt handling mode:
	// - 'default': Use base system prompt only (customSystemPrompt ignored)
	// - 'append': Append customSystemPrompt to base system prompt (50KB limit)
	// - 'replace': Replace base system prompt with customSystemPrompt (100KB limit)
	PromptMode *PromptMode `default:"default" json:"promptMode"`
	// Session type. API can only create 'main' sessions. Subagent sessions are created automatically by the task delegation system.
	SessionType *SessionType `default:"main" json:"sessionType"`
	// Subagent type - must not be set for API-created sessions. This field is reserved for programmatic subagent creation.
	SubagentType *string `json:"subagentType,omitempty"`
	// Title for the session
	Title string `json:"title"`
}

func (c CreateSessionRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateSessionRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateSessionRequest) GetCallbacks() []components.Callback {
	if c == nil {
		return nil
	}
	return c.Callbacks
}

func (c *CreateSessionRequest) GetCustomSystemPrompt() *string {
	if c == nil {
		return nil
	}
	return c.CustomSystemPrompt
}

func (c *CreateSessionRequest) GetPromptMode() *PromptMode {
	if c == nil {
		return nil
	}
	return c.PromptMode
}

func (c *CreateSessionRequest) GetSessionType() *SessionType {
	if c == nil {
		return nil
	}
	return c.SessionType
}

func (c *CreateSessionRequest) GetSubagentType() *string {
	if c == nil {
		return nil
	}
	return c.SubagentType
}

func (c *CreateSessionRequest) GetTitle() string {
	if c == nil {
		return ""
	}
	return c.Title
}

type CreateSessionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created session
	SessionData *components.SessionData
}

func (c *CreateSessionResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateSessionResponse) GetSessionData() *components.SessionData {
	if c == nil {
		return nil
	}
	return c.SessionData
}
