// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type DeleteSessionFileRequest struct {
	// Session ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Filename to delete
	Filename string `pathParam:"style=simple,explode=false,name=filename"`
}

func (d *DeleteSessionFileRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeleteSessionFileRequest) GetFilename() string {
	if d == nil {
		return ""
	}
	return d.Filename
}

type DeleteSessionFileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteSessionFileResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
