// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type DeleteSessionRequest struct {
	// Session ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteSessionRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteSessionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteSessionResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
