// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type DeleteCredentialsRequest struct {
	// Provider name (anthropic, openai, openrouter, gemini, brave)
	Provider string `pathParam:"style=simple,explode=false,name=provider"`
}

func (d *DeleteCredentialsRequest) GetProvider() string {
	if d == nil {
		return ""
	}
	return d.Provider
}

// DeleteCredentialsResponseBody - Credentials deletion status
type DeleteCredentialsResponseBody struct {
	// Status message
	Message *string `json:"message,omitempty"`
	// Provider name
	Provider *string `json:"provider,omitempty"`
	// Operation status
	Status *string `json:"status,omitempty"`
}

func (d *DeleteCredentialsResponseBody) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

func (d *DeleteCredentialsResponseBody) GetProvider() *string {
	if d == nil {
		return nil
	}
	return d.Provider
}

func (d *DeleteCredentialsResponseBody) GetStatus() *string {
	if d == nil {
		return nil
	}
	return d.Status
}

type DeleteCredentialsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Credentials deletion status
	Object *DeleteCredentialsResponseBody
}

func (d *DeleteCredentialsResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteCredentialsResponse) GetObject() *DeleteCredentialsResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
