// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type DenyPermissionRequest struct {
	// Permission ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DenyPermissionRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

// DenyPermissionResponseBody - Permission deny status
type DenyPermissionResponseBody struct {
	// Whether permission was denied
	Denied *bool `json:"denied,omitempty"`
}

func (d *DenyPermissionResponseBody) GetDenied() *bool {
	if d == nil {
		return nil
	}
	return d.Denied
}

type DenyPermissionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Permission deny status
	Object *DenyPermissionResponseBody
}

func (d *DenyPermissionResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DenyPermissionResponse) GetObject() *DenyPermissionResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
