// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type ExportSessionRequest struct {
	// Session ID to export
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (e *ExportSessionRequest) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

type ExportSessionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Session transcript exported successfully
	ExportSession *components.ExportSession
	Headers       map[string][]string
}

func (e *ExportSessionResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *ExportSessionResponse) GetExportSession() *components.ExportSession {
	if e == nil {
		return nil
	}
	return e.ExportSession
}

func (e *ExportSessionResponse) GetHeaders() map[string][]string {
	if e == nil {
		return map[string][]string{}
	}
	return e.Headers
}
