// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type ForkSessionRequestBody struct {
	// Index of the last message to include in the fork (0-based)
	MessageIndex int64 `json:"messageIndex"`
	// Optional title for the forked session (defaults to 'Forked Session')
	Title *string `json:"title,omitempty"`
}

func (f *ForkSessionRequestBody) GetMessageIndex() int64 {
	if f == nil {
		return 0
	}
	return f.MessageIndex
}

func (f *ForkSessionRequestBody) GetTitle() *string {
	if f == nil {
		return nil
	}
	return f.Title
}

type ForkSessionRequest struct {
	// Source session ID to fork from
	ID          string                 `pathParam:"style=simple,explode=false,name=id"`
	RequestBody ForkSessionRequestBody `request:"mediaType=application/json"`
}

func (f *ForkSessionRequest) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *ForkSessionRequest) GetRequestBody() ForkSessionRequestBody {
	if f == nil {
		return ForkSessionRequestBody{}
	}
	return f.RequestBody
}

type ForkSessionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Forked session
	SessionData *components.SessionData
}

func (f *ForkSessionResponse) GetHTTPMeta() components.HTTPMetadata {
	if f == nil {
		return components.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *ForkSessionResponse) GetSessionData() *components.SessionData {
	if f == nil {
		return nil
	}
	return f.SessionData
}
