// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/recreate-run/mix-go-sdk/models/components"
)

// GetAuthStatusAuthMethod - Authentication method (oauth, api_key, none)
type GetAuthStatusAuthMethod string

const (
	GetAuthStatusAuthMethodOauth  GetAuthStatusAuthMethod = "oauth"
	GetAuthStatusAuthMethodAPIKey GetAuthStatusAuthMethod = "api_key"
	GetAuthStatusAuthMethodNone   GetAuthStatusAuthMethod = "none"
)

func (e GetAuthStatusAuthMethod) ToPointer() *GetAuthStatusAuthMethod {
	return &e
}
func (e *GetAuthStatusAuthMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "oauth":
		fallthrough
	case "api_key":
		fallthrough
	case "none":
		*e = GetAuthStatusAuthMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAuthStatusAuthMethod: %v", v)
	}
}

type GetAuthStatusProviders struct {
	// Authentication method (oauth, api_key, none)
	AuthMethod *GetAuthStatusAuthMethod `json:"auth_method,omitempty"`
	// Whether provider is authenticated
	Authenticated *bool `json:"authenticated,omitempty"`
	// User-friendly provider name
	DisplayName *string `json:"display_name,omitempty"`
}

func (g *GetAuthStatusProviders) GetAuthMethod() *GetAuthStatusAuthMethod {
	if g == nil {
		return nil
	}
	return g.AuthMethod
}

func (g *GetAuthStatusProviders) GetAuthenticated() *bool {
	if g == nil {
		return nil
	}
	return g.Authenticated
}

func (g *GetAuthStatusProviders) GetDisplayName() *string {
	if g == nil {
		return nil
	}
	return g.DisplayName
}

// GetAuthStatusResponseBody - Authentication status for all providers
type GetAuthStatusResponseBody struct {
	// Map of provider authentication status
	Providers map[string]GetAuthStatusProviders `json:"providers,omitempty"`
}

func (g *GetAuthStatusResponseBody) GetProviders() map[string]GetAuthStatusProviders {
	if g == nil {
		return nil
	}
	return g.Providers
}

type GetAuthStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Authentication status for all providers
	Object *GetAuthStatusResponseBody
}

func (g *GetAuthStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAuthStatusResponse) GetObject() *GetAuthStatusResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
