// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type GetAvailableProvidersResponseBody struct {
	// Provider display name
	DisplayName *string `json:"display_name,omitempty"`
	// Available models for this provider
	Models []string `json:"models,omitempty"`
}

func (g *GetAvailableProvidersResponseBody) GetDisplayName() *string {
	if g == nil {
		return nil
	}
	return g.DisplayName
}

func (g *GetAvailableProvidersResponseBody) GetModels() []string {
	if g == nil {
		return nil
	}
	return g.Models
}

type GetAvailableProvidersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Available providers
	Object map[string]GetAvailableProvidersResponseBody
}

func (g *GetAvailableProvidersResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAvailableProvidersResponse) GetObject() map[string]GetAvailableProvidersResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
