// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type GetCommandRequest struct {
	// Command name
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

func (g *GetCommandRequest) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

// GetCommandResponseBody - Command details
type GetCommandResponseBody struct {
	// Command description
	Description *string `json:"description,omitempty"`
	// Command name
	Name *string `json:"name,omitempty"`
	// Command usage instructions
	Usage *string `json:"usage,omitempty"`
}

func (g *GetCommandResponseBody) GetDescription() *string {
	if g == nil {
		return nil
	}
	return g.Description
}

func (g *GetCommandResponseBody) GetName() *string {
	if g == nil {
		return nil
	}
	return g.Name
}

func (g *GetCommandResponseBody) GetUsage() *string {
	if g == nil {
		return nil
	}
	return g.Usage
}

type GetCommandResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Command details
	Object *GetCommandResponseBody
}

func (g *GetCommandResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCommandResponse) GetObject() *GetCommandResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
