// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/internal/utils"
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type GetMessageHistoryRequest struct {
	// Maximum number of messages to return
	Limit *int64 `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Number of messages to skip
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (g GetMessageHistoryRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMessageHistoryRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMessageHistoryRequest) GetLimit() *int64 {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GetMessageHistoryRequest) GetOffset() *int64 {
	if g == nil {
		return nil
	}
	return g.Offset
}

type GetMessageHistoryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Message history
	BackendMessages []components.BackendMessage
}

func (g *GetMessageHistoryResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMessageHistoryResponse) GetBackendMessages() []components.BackendMessage {
	if g == nil {
		return nil
	}
	return g.BackendMessages
}
