// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/recreate-run/mix-go-sdk/internal/utils"
	"github.com/recreate-run/mix-go-sdk/models/components"
	"time"
)

// ProvidersStatus - Token status
type ProvidersStatus string

const (
	ProvidersStatusActive           ProvidersStatus = "active"
	ProvidersStatusExpired          ProvidersStatus = "expired"
	ProvidersStatusExpiredNoRefresh ProvidersStatus = "expired_no_refresh"
	ProvidersStatusError            ProvidersStatus = "error"
	ProvidersStatusNotFound         ProvidersStatus = "not_found"
)

func (e ProvidersStatus) ToPointer() *ProvidersStatus {
	return &e
}
func (e *ProvidersStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "active":
		fallthrough
	case "expired":
		fallthrough
	case "expired_no_refresh":
		fallthrough
	case "error":
		fallthrough
	case "not_found":
		*e = ProvidersStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProvidersStatus: %v", v)
	}
}

type GetOAuthHealthProviders struct {
	// Error message if status is 'error'
	Error *string `json:"error,omitempty"`
	// Token expiration time
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Human-readable time until expiration
	ExpiresIn *string `json:"expires_in,omitempty"`
	// Last time token was refreshed
	LastRefresh *time.Time `json:"last_refresh,omitempty"`
	// Provider name
	Provider string `json:"provider"`
	// Token status
	Status ProvidersStatus `json:"status"`
}

func (g GetOAuthHealthProviders) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetOAuthHealthProviders) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetOAuthHealthProviders) GetError() *string {
	if g == nil {
		return nil
	}
	return g.Error
}

func (g *GetOAuthHealthProviders) GetExpiresAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.ExpiresAt
}

func (g *GetOAuthHealthProviders) GetExpiresIn() *string {
	if g == nil {
		return nil
	}
	return g.ExpiresIn
}

func (g *GetOAuthHealthProviders) GetLastRefresh() *time.Time {
	if g == nil {
		return nil
	}
	return g.LastRefresh
}

func (g *GetOAuthHealthProviders) GetProvider() string {
	if g == nil {
		return ""
	}
	return g.Provider
}

func (g *GetOAuthHealthProviders) GetStatus() ProvidersStatus {
	if g == nil {
		return ProvidersStatus("")
	}
	return g.Status
}

// Status - Overall health status
type Status string

const (
	StatusHealthy   Status = "healthy"
	StatusDegraded  Status = "degraded"
	StatusUnhealthy Status = "unhealthy"
)

func (e Status) ToPointer() *Status {
	return &e
}
func (e *Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "healthy":
		fallthrough
	case "degraded":
		fallthrough
	case "unhealthy":
		*e = Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status: %v", v)
	}
}

// GetOAuthHealthResponseBody - OAuth health status
type GetOAuthHealthResponseBody struct {
	// Map of provider OAuth health status
	Providers map[string]GetOAuthHealthProviders `json:"providers"`
	// Overall health status
	Status Status `json:"status"`
	// Health check timestamp
	Timestamp time.Time `json:"timestamp"`
}

func (g GetOAuthHealthResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetOAuthHealthResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetOAuthHealthResponseBody) GetProviders() map[string]GetOAuthHealthProviders {
	if g == nil {
		return map[string]GetOAuthHealthProviders{}
	}
	return g.Providers
}

func (g *GetOAuthHealthResponseBody) GetStatus() Status {
	if g == nil {
		return Status("")
	}
	return g.Status
}

func (g *GetOAuthHealthResponseBody) GetTimestamp() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.Timestamp
}

type GetOAuthHealthResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OAuth health status
	Object *GetOAuthHealthResponseBody
}

func (g *GetOAuthHealthResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetOAuthHealthResponse) GetObject() *GetOAuthHealthResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
