// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
	"github.com/recreate-run/mix-go-sdk/optionalnullable"
)

type AvailableProviders struct {
	// User-friendly provider name
	DisplayName *string `json:"display_name,omitempty"`
	// Available models from this provider
	Models []string `json:"models,omitempty"`
}

func (a *AvailableProviders) GetDisplayName() *string {
	if a == nil {
		return nil
	}
	return a.DisplayName
}

func (a *AvailableProviders) GetModels() []string {
	if a == nil {
		return nil
	}
	return a.Models
}

// Preferences - User preferences (null if no preferences exist)
type Preferences struct {
	// Unix timestamp when preferences were created
	CreatedAt *int64 `json:"created_at,omitempty"`
	// Maximum tokens for main agent responses
	MainAgentMaxTokens *int64 `json:"main_agent_max_tokens,omitempty"`
	// Main agent model ID
	MainAgentModel *string `json:"main_agent_model,omitempty"`
	// Reasoning effort setting for main agent
	MainAgentReasoningEffort *string `json:"main_agent_reasoning_effort,omitempty"`
	// Preferred AI provider (anthropic, openai, openrouter)
	PreferredProvider *string `json:"preferred_provider,omitempty"`
	// Maximum tokens for sub agent responses
	SubAgentMaxTokens *int64 `json:"sub_agent_max_tokens,omitempty"`
	// Sub agent model ID
	SubAgentModel *string `json:"sub_agent_model,omitempty"`
	// Reasoning effort setting for sub agent
	SubAgentReasoningEffort *string `json:"sub_agent_reasoning_effort,omitempty"`
	// Unix timestamp of last update
	UpdatedAt *int64 `json:"updated_at,omitempty"`
}

func (p *Preferences) GetCreatedAt() *int64 {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *Preferences) GetMainAgentMaxTokens() *int64 {
	if p == nil {
		return nil
	}
	return p.MainAgentMaxTokens
}

func (p *Preferences) GetMainAgentModel() *string {
	if p == nil {
		return nil
	}
	return p.MainAgentModel
}

func (p *Preferences) GetMainAgentReasoningEffort() *string {
	if p == nil {
		return nil
	}
	return p.MainAgentReasoningEffort
}

func (p *Preferences) GetPreferredProvider() *string {
	if p == nil {
		return nil
	}
	return p.PreferredProvider
}

func (p *Preferences) GetSubAgentMaxTokens() *int64 {
	if p == nil {
		return nil
	}
	return p.SubAgentMaxTokens
}

func (p *Preferences) GetSubAgentModel() *string {
	if p == nil {
		return nil
	}
	return p.SubAgentModel
}

func (p *Preferences) GetSubAgentReasoningEffort() *string {
	if p == nil {
		return nil
	}
	return p.SubAgentReasoningEffort
}

func (p *Preferences) GetUpdatedAt() *int64 {
	if p == nil {
		return nil
	}
	return p.UpdatedAt
}

// GetPreferencesResponseBody - User preferences and available providers
type GetPreferencesResponseBody struct {
	// Map of available AI providers and their models
	AvailableProviders map[string]AvailableProviders `json:"available_providers"`
	// User preferences (null if no preferences exist)
	Preferences optionalnullable.OptionalNullable[Preferences] `json:"preferences,omitempty"`
}

func (g *GetPreferencesResponseBody) GetAvailableProviders() map[string]AvailableProviders {
	if g == nil {
		return map[string]AvailableProviders{}
	}
	return g.AvailableProviders
}

func (g *GetPreferencesResponseBody) GetPreferences() optionalnullable.OptionalNullable[Preferences] {
	if g == nil {
		return nil
	}
	return g.Preferences
}

type GetPreferencesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// User preferences and available providers
	Object *GetPreferencesResponseBody
}

func (g *GetPreferencesResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPreferencesResponse) GetObject() *GetPreferencesResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
