// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type AvailableProviders struct {
	// User-friendly provider name
	DisplayName *string `json:"display_name,omitempty"`
	// Available models from this provider
	Models []string `json:"models,omitempty"`
}

func (a *AvailableProviders) GetDisplayName() *string {
	if a == nil {
		return nil
	}
	return a.DisplayName
}

func (a *AvailableProviders) GetModels() []string {
	if a == nil {
		return nil
	}
	return a.Models
}

// GetPreferencesResponseBody - User preferences and available providers
type GetPreferencesResponseBody struct {
	// Map of available AI providers and their models
	AvailableProviders map[string]AvailableProviders `json:"available_providers"`
	// User preferences configuration
	Preferences *components.UserPreferencesResponse `json:"preferences,omitempty"`
}

func (g *GetPreferencesResponseBody) GetAvailableProviders() map[string]AvailableProviders {
	if g == nil {
		return map[string]AvailableProviders{}
	}
	return g.AvailableProviders
}

func (g *GetPreferencesResponseBody) GetPreferences() *components.UserPreferencesResponse {
	if g == nil {
		return nil
	}
	return g.Preferences
}

type GetPreferencesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// User preferences and available providers
	Object *GetPreferencesResponseBody
}

func (g *GetPreferencesResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPreferencesResponse) GetObject() *GetPreferencesResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
