// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type GetSessionMessagesRequest struct {
	// Session ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetSessionMessagesRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetSessionMessagesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of session messages
	BackendMessages []components.BackendMessage
}

func (g *GetSessionMessagesResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSessionMessagesResponse) GetBackendMessages() []components.BackendMessage {
	if g == nil {
		return nil
	}
	return g.BackendMessages
}
