// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
	"io"
)

type GetSessionFileRequest struct {
	// Session ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Filename to retrieve
	Filename string `pathParam:"style=simple,explode=false,name=filename"`
	// Thumbnail specification: '100' (box), 'w100' (width), 'h100' (height)
	Thumb *string `queryParam:"style=form,explode=true,name=thumb"`
	// Time offset in seconds for video thumbnails (default: 1.0)
	Time *float64 `queryParam:"style=form,explode=true,name=time"`
}

func (g *GetSessionFileRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetSessionFileRequest) GetFilename() string {
	if g == nil {
		return ""
	}
	return g.Filename
}

func (g *GetSessionFileRequest) GetThumb() *string {
	if g == nil {
		return nil
	}
	return g.Thumb
}

func (g *GetSessionFileRequest) GetTime() *float64 {
	if g == nil {
		return nil
	}
	return g.Time
}

type GetSessionFileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// File content
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
}

func (g *GetSessionFileResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSessionFileResponse) GetResponseStream() io.ReadCloser {
	if g == nil {
		return nil
	}
	return g.ResponseStream
}
