// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

// GetSystemInfoResponseBody - System information
type GetSystemInfoResponseBody struct {
	// Absolute path to the storage base directory
	StorageBasePath string `json:"storageBasePath"`
}

func (g *GetSystemInfoResponseBody) GetStorageBasePath() string {
	if g == nil {
		return ""
	}
	return g.StorageBasePath
}

type GetSystemInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// System information
	Object *GetSystemInfoResponseBody
}

func (g *GetSystemInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSystemInfoResponse) GetObject() *GetSystemInfoResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
