// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type GetSessionRequest struct {
	// Session ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetSessionRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetSessionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Session details
	SessionData *components.SessionData
}

func (g *GetSessionResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSessionResponse) GetSessionData() *components.SessionData {
	if g == nil {
		return nil
	}
	return g.SessionData
}
