// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type GetToolCredentialsStatusTool struct {
	// Expected API key format
	APIKeyFormat *string `json:"api_key_format,omitempty"`
	// Whether an API key is required
	APIKeyRequired *bool `json:"api_key_required,omitempty"`
	// Whether the tool has valid credentials
	Authenticated *bool `json:"authenticated,omitempty"`
	// Tool description
	Description *string `json:"description,omitempty"`
	// Tool display name
	DisplayName *string `json:"display_name,omitempty"`
	// Provider identifier
	Provider *string `json:"provider,omitempty"`
}

func (g *GetToolCredentialsStatusTool) GetAPIKeyFormat() *string {
	if g == nil {
		return nil
	}
	return g.APIKeyFormat
}

func (g *GetToolCredentialsStatusTool) GetAPIKeyRequired() *bool {
	if g == nil {
		return nil
	}
	return g.APIKeyRequired
}

func (g *GetToolCredentialsStatusTool) GetAuthenticated() *bool {
	if g == nil {
		return nil
	}
	return g.Authenticated
}

func (g *GetToolCredentialsStatusTool) GetDescription() *string {
	if g == nil {
		return nil
	}
	return g.Description
}

func (g *GetToolCredentialsStatusTool) GetDisplayName() *string {
	if g == nil {
		return nil
	}
	return g.DisplayName
}

func (g *GetToolCredentialsStatusTool) GetProvider() *string {
	if g == nil {
		return nil
	}
	return g.Provider
}

type GetToolCredentialsStatusCategories struct {
	// Category description
	Description *string `json:"description,omitempty"`
	// Category display name
	DisplayName *string `json:"display_name,omitempty"`
	// Category icon
	Icon *string `json:"icon,omitempty"`
	// Tools in this category
	Tools []GetToolCredentialsStatusTool `json:"tools,omitempty"`
}

func (g *GetToolCredentialsStatusCategories) GetDescription() *string {
	if g == nil {
		return nil
	}
	return g.Description
}

func (g *GetToolCredentialsStatusCategories) GetDisplayName() *string {
	if g == nil {
		return nil
	}
	return g.DisplayName
}

func (g *GetToolCredentialsStatusCategories) GetIcon() *string {
	if g == nil {
		return nil
	}
	return g.Icon
}

func (g *GetToolCredentialsStatusCategories) GetTools() []GetToolCredentialsStatusTool {
	if g == nil {
		return nil
	}
	return g.Tools
}

// GetToolCredentialsStatusResponseBody - Tool credentials status
type GetToolCredentialsStatusResponseBody struct {
	// Tool categories grouped by type
	Categories map[string]GetToolCredentialsStatusCategories `json:"categories,omitempty"`
}

func (g *GetToolCredentialsStatusResponseBody) GetCategories() map[string]GetToolCredentialsStatusCategories {
	if g == nil {
		return nil
	}
	return g.Categories
}

type GetToolCredentialsStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Tool credentials status
	Object *GetToolCredentialsStatusResponseBody
}

func (g *GetToolCredentialsStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetToolCredentialsStatusResponse) GetObject() *GetToolCredentialsStatusResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
