// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type GetToolsStatusTool struct {
	// Whether tool requires API key authentication
	APIKeyRequired *bool `json:"api_key_required,omitempty"`
	// Whether tool is authenticated and ready to use
	Authenticated *bool `json:"authenticated,omitempty"`
	// Tool description
	Description *string `json:"description,omitempty"`
	// User-friendly tool name
	DisplayName *string `json:"display_name,omitempty"`
	// Tool provider name
	Provider *string `json:"provider,omitempty"`
}

func (g *GetToolsStatusTool) GetAPIKeyRequired() *bool {
	if g == nil {
		return nil
	}
	return g.APIKeyRequired
}

func (g *GetToolsStatusTool) GetAuthenticated() *bool {
	if g == nil {
		return nil
	}
	return g.Authenticated
}

func (g *GetToolsStatusTool) GetDescription() *string {
	if g == nil {
		return nil
	}
	return g.Description
}

func (g *GetToolsStatusTool) GetDisplayName() *string {
	if g == nil {
		return nil
	}
	return g.DisplayName
}

func (g *GetToolsStatusTool) GetProvider() *string {
	if g == nil {
		return nil
	}
	return g.Provider
}

type GetToolsStatusCategories struct {
	// User-friendly category name
	DisplayName *string `json:"display_name,omitempty"`
	// Available tools in this category
	Tools []GetToolsStatusTool `json:"tools,omitempty"`
}

func (g *GetToolsStatusCategories) GetDisplayName() *string {
	if g == nil {
		return nil
	}
	return g.DisplayName
}

func (g *GetToolsStatusCategories) GetTools() []GetToolsStatusTool {
	if g == nil {
		return nil
	}
	return g.Tools
}

// GetToolsStatusResponseBody - Tools status and authentication information
type GetToolsStatusResponseBody struct {
	// Map of tool categories and their tools
	Categories map[string]GetToolsStatusCategories `json:"categories,omitempty"`
}

func (g *GetToolsStatusResponseBody) GetCategories() map[string]GetToolsStatusCategories {
	if g == nil {
		return nil
	}
	return g.Categories
}

type GetToolsStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Tools status and authentication information
	Object *GetToolsStatusResponseBody
}

func (g *GetToolsStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetToolsStatusResponse) GetObject() *GetToolsStatusResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
