// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type GrantPermissionRequest struct {
	// Permission ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GrantPermissionRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

// GrantPermissionResponseBody - Permission grant status
type GrantPermissionResponseBody struct {
	// Whether permission was granted
	Granted *bool `json:"granted,omitempty"`
}

func (g *GrantPermissionResponseBody) GetGranted() *bool {
	if g == nil {
		return nil
	}
	return g.Granted
}

type GrantPermissionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Permission grant status
	Object *GrantPermissionResponseBody
}

func (g *GrantPermissionResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GrantPermissionResponse) GetObject() *GrantPermissionResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
