// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type HandleOAuthCallbackRequest struct {
	// Authorization code from OAuth provider
	Code string `json:"code"`
	// Provider name (anthropic)
	Provider string `json:"provider"`
	// OAuth state for verification
	State string `json:"state"`
}

func (h *HandleOAuthCallbackRequest) GetCode() string {
	if h == nil {
		return ""
	}
	return h.Code
}

func (h *HandleOAuthCallbackRequest) GetProvider() string {
	if h == nil {
		return ""
	}
	return h.Provider
}

func (h *HandleOAuthCallbackRequest) GetState() string {
	if h == nil {
		return ""
	}
	return h.State
}

// HandleOAuthCallbackResponseBody - OAuth completion status
type HandleOAuthCallbackResponseBody struct {
	// Seconds until token expiration
	ExpiresIn *int64 `json:"expires_in,omitempty"`
	// Status message
	Message *string `json:"message,omitempty"`
	// Provider name
	Provider *string `json:"provider,omitempty"`
	// Operation status
	Status *string `json:"status,omitempty"`
}

func (h *HandleOAuthCallbackResponseBody) GetExpiresIn() *int64 {
	if h == nil {
		return nil
	}
	return h.ExpiresIn
}

func (h *HandleOAuthCallbackResponseBody) GetMessage() *string {
	if h == nil {
		return nil
	}
	return h.Message
}

func (h *HandleOAuthCallbackResponseBody) GetProvider() *string {
	if h == nil {
		return nil
	}
	return h.Provider
}

func (h *HandleOAuthCallbackResponseBody) GetStatus() *string {
	if h == nil {
		return nil
	}
	return h.Status
}

type HandleOAuthCallbackResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OAuth completion status
	Object *HandleOAuthCallbackResponseBody
}

func (h *HandleOAuthCallbackResponse) GetHTTPMeta() components.HTTPMetadata {
	if h == nil {
		return components.HTTPMetadata{}
	}
	return h.HTTPMeta
}

func (h *HandleOAuthCallbackResponse) GetObject() *HandleOAuthCallbackResponseBody {
	if h == nil {
		return nil
	}
	return h.Object
}
