// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

// HealthCheckResponseBody - Health information
type HealthCheckResponseBody struct {
	// Health status
	Status *string `json:"status,omitempty"`
	// Current timestamp
	Timestamp *string `json:"timestamp,omitempty"`
	// Application version
	Version *string `json:"version,omitempty"`
}

func (h *HealthCheckResponseBody) GetStatus() *string {
	if h == nil {
		return nil
	}
	return h.Status
}

func (h *HealthCheckResponseBody) GetTimestamp() *string {
	if h == nil {
		return nil
	}
	return h.Timestamp
}

func (h *HealthCheckResponseBody) GetVersion() *string {
	if h == nil {
		return nil
	}
	return h.Version
}

type HealthCheckResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Health information
	Object *HealthCheckResponseBody
}

func (h *HealthCheckResponse) GetHTTPMeta() components.HTTPMetadata {
	if h == nil {
		return components.HTTPMetadata{}
	}
	return h.HTTPMeta
}

func (h *HealthCheckResponse) GetObject() *HealthCheckResponseBody {
	if h == nil {
		return nil
	}
	return h.Object
}
