// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/internal/utils"
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type ListSessionsRequest struct {
	// Include subagent sessions in response (default: false, subagent sessions are hidden)
	IncludeSubagents *bool `default:"false" queryParam:"style=form,explode=true,name=includeSubagents"`
}

func (l ListSessionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSessionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSessionsRequest) GetIncludeSubagents() *bool {
	if l == nil {
		return nil
	}
	return l.IncludeSubagents
}

type ListSessionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of sessions
	SessionData []components.SessionData
}

func (l *ListSessionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSessionsResponse) GetSessionData() []components.SessionData {
	if l == nil {
		return nil
	}
	return l.SessionData
}
