// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type ListSessionFilesRequest struct {
	// Session ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (l *ListSessionFilesRequest) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

type ListSessionFilesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of files in session
	FileInfos []components.FileInfo
}

func (l *ListSessionFilesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSessionFilesResponse) GetFileInfos() []components.FileInfo {
	if l == nil {
		return nil
	}
	return l.FileInfos
}
