// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type ListCommandsResponseBody struct {
	// Command description
	Description *string `json:"description,omitempty"`
	// Command name
	Name *string `json:"name,omitempty"`
}

func (l *ListCommandsResponseBody) GetDescription() *string {
	if l == nil {
		return nil
	}
	return l.Description
}

func (l *ListCommandsResponseBody) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

type ListCommandsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of commands
	ResponseBodies []ListCommandsResponseBody
}

func (l *ListCommandsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListCommandsResponse) GetResponseBodies() []ListCommandsResponseBody {
	if l == nil {
		return nil
	}
	return l.ResponseBodies
}
