// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

// Parameters - Tool parameter schema
type Parameters struct {
}

type ListLLMToolsTool struct {
	// Tool description
	Description *string `json:"description,omitempty"`
	// Tool name
	Name *string `json:"name,omitempty"`
	// Tool parameter schema
	Parameters *Parameters `json:"parameters,omitempty"`
	// Required parameters
	Required []string `json:"required,omitempty"`
}

func (l *ListLLMToolsTool) GetDescription() *string {
	if l == nil {
		return nil
	}
	return l.Description
}

func (l *ListLLMToolsTool) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *ListLLMToolsTool) GetParameters() *Parameters {
	if l == nil {
		return nil
	}
	return l.Parameters
}

func (l *ListLLMToolsTool) GetRequired() []string {
	if l == nil {
		return nil
	}
	return l.Required
}

// ListLLMToolsResponseBody - List of LLM tools
type ListLLMToolsResponseBody struct {
	Tools []ListLLMToolsTool `json:"tools,omitempty"`
}

func (l *ListLLMToolsResponseBody) GetTools() []ListLLMToolsTool {
	if l == nil {
		return nil
	}
	return l.Tools
}

type ListLLMToolsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of LLM tools
	Object *ListLLMToolsResponseBody
}

func (l *ListLLMToolsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListLLMToolsResponse) GetObject() *ListLLMToolsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
