// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

// RefreshOAuthTokensResponseBody - Token refresh triggered
type RefreshOAuthTokensResponseBody struct {
	// Status message
	Message *string `json:"message,omitempty"`
	// Operation status
	Status *string `json:"status,omitempty"`
}

func (r *RefreshOAuthTokensResponseBody) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

func (r *RefreshOAuthTokensResponseBody) GetStatus() *string {
	if r == nil {
		return nil
	}
	return r.Status
}

type RefreshOAuthTokensResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Token refresh triggered
	Object *RefreshOAuthTokensResponseBody
}

func (r *RefreshOAuthTokensResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RefreshOAuthTokensResponse) GetObject() *RefreshOAuthTokensResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
