// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

// ResetPreferencesResponseBody - Reset preferences
type ResetPreferencesResponseBody struct {
	// Creation timestamp
	CreatedAt *int64 `json:"created_at,omitempty"`
	// Reset main agent max tokens
	MainAgentMaxTokens *int64 `json:"main_agent_max_tokens,omitempty"`
	// Reset main agent model
	MainAgentModel *string `json:"main_agent_model,omitempty"`
	// Reset main agent reasoning effort
	MainAgentReasoningEffort *string `json:"main_agent_reasoning_effort,omitempty"`
	// Reset preferred provider
	PreferredProvider *string `json:"preferred_provider,omitempty"`
	// Reset sub agent max tokens
	SubAgentMaxTokens *int64 `json:"sub_agent_max_tokens,omitempty"`
	// Reset sub agent model
	SubAgentModel *string `json:"sub_agent_model,omitempty"`
	// Reset sub agent reasoning effort
	SubAgentReasoningEffort *string `json:"sub_agent_reasoning_effort,omitempty"`
	// Reset timestamp
	UpdatedAt *int64 `json:"updated_at,omitempty"`
}

func (r *ResetPreferencesResponseBody) GetCreatedAt() *int64 {
	if r == nil {
		return nil
	}
	return r.CreatedAt
}

func (r *ResetPreferencesResponseBody) GetMainAgentMaxTokens() *int64 {
	if r == nil {
		return nil
	}
	return r.MainAgentMaxTokens
}

func (r *ResetPreferencesResponseBody) GetMainAgentModel() *string {
	if r == nil {
		return nil
	}
	return r.MainAgentModel
}

func (r *ResetPreferencesResponseBody) GetMainAgentReasoningEffort() *string {
	if r == nil {
		return nil
	}
	return r.MainAgentReasoningEffort
}

func (r *ResetPreferencesResponseBody) GetPreferredProvider() *string {
	if r == nil {
		return nil
	}
	return r.PreferredProvider
}

func (r *ResetPreferencesResponseBody) GetSubAgentMaxTokens() *int64 {
	if r == nil {
		return nil
	}
	return r.SubAgentMaxTokens
}

func (r *ResetPreferencesResponseBody) GetSubAgentModel() *string {
	if r == nil {
		return nil
	}
	return r.SubAgentModel
}

func (r *ResetPreferencesResponseBody) GetSubAgentReasoningEffort() *string {
	if r == nil {
		return nil
	}
	return r.SubAgentReasoningEffort
}

func (r *ResetPreferencesResponseBody) GetUpdatedAt() *int64 {
	if r == nil {
		return nil
	}
	return r.UpdatedAt
}

type ResetPreferencesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Reset preferences
	Object *ResetPreferencesResponseBody
}

func (r *ResetPreferencesResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ResetPreferencesResponse) GetObject() *ResetPreferencesResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
