// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/recreate-run/mix-go-sdk/models/components"
)

// Type - Response type
type Type string

const (
	TypeAcknowledge Type = "acknowledge"
	TypeText        Type = "text"
	TypeChoice      Type = "choice"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "acknowledge":
		fallthrough
	case "text":
		fallthrough
	case "choice":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type RespondToNotificationRequestBody struct {
	// Response type
	Type Type `json:"type"`
	// User's text input or selected choice (optional for acknowledge type)
	Value *string `json:"value,omitempty"`
}

func (r *RespondToNotificationRequestBody) GetType() Type {
	if r == nil {
		return Type("")
	}
	return r.Type
}

func (r *RespondToNotificationRequestBody) GetValue() *string {
	if r == nil {
		return nil
	}
	return r.Value
}

type RespondToNotificationRequest struct {
	// Notification ID
	ID          string                           `pathParam:"style=simple,explode=false,name=id"`
	RequestBody RespondToNotificationRequestBody `request:"mediaType=application/json"`
}

func (r *RespondToNotificationRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RespondToNotificationRequest) GetRequestBody() RespondToNotificationRequestBody {
	if r == nil {
		return RespondToNotificationRequestBody{}
	}
	return r.RequestBody
}

type RespondToNotificationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (r *RespondToNotificationResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}
