// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/internal/utils"
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type RewindSessionRequestBody struct {
	// Whether to clean up media files created after the rewind point (based on file timestamp)
	CleanupMedia *bool `default:"true" json:"cleanupMedia"`
	// ID of the last message to keep. All messages after this message will be deleted.
	MessageID string `json:"messageId"`
}

func (r RewindSessionRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RewindSessionRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"messageId"}); err != nil {
		return err
	}
	return nil
}

func (r *RewindSessionRequestBody) GetCleanupMedia() *bool {
	if r == nil {
		return nil
	}
	return r.CleanupMedia
}

func (r *RewindSessionRequestBody) GetMessageID() string {
	if r == nil {
		return ""
	}
	return r.MessageID
}

type RewindSessionRequest struct {
	// Session ID to rewind
	ID          string                   `pathParam:"style=simple,explode=false,name=id"`
	RequestBody RewindSessionRequestBody `request:"mediaType=application/json"`
}

func (r *RewindSessionRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RewindSessionRequest) GetRequestBody() RewindSessionRequestBody {
	if r == nil {
		return RewindSessionRequestBody{}
	}
	return r.RequestBody
}

type RewindSessionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Session rewound successfully
	SessionData *components.SessionData
}

func (r *RewindSessionResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RewindSessionResponse) GetSessionData() *components.SessionData {
	if r == nil {
		return nil
	}
	return r.SessionData
}
