// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/recreate-run/mix-go-sdk/internal/utils"
	"github.com/recreate-run/mix-go-sdk/models/components"
	"github.com/recreate-run/mix-go-sdk/optionalnullable"
)

// ThinkingLevel - Thinking level: off (disabled), basic (4k tokens), medium (10k tokens), maximum (32k tokens). If not provided, determined by keywords in message.
type ThinkingLevel string

const (
	ThinkingLevelOff     ThinkingLevel = "off"
	ThinkingLevelBasic   ThinkingLevel = "basic"
	ThinkingLevelMedium  ThinkingLevel = "medium"
	ThinkingLevelMaximum ThinkingLevel = "maximum"
)

func (e ThinkingLevel) ToPointer() *ThinkingLevel {
	return &e
}
func (e *ThinkingLevel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "off":
		fallthrough
	case "basic":
		fallthrough
	case "medium":
		fallthrough
	case "maximum":
		*e = ThinkingLevel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ThinkingLevel: %v", v)
	}
}

type SendMessageRequestBody struct {
	// Whether the message is in planning mode
	PlanMode *bool `default:"false" json:"plan_mode"`
	// The text content of the message
	Text string `json:"text"`
	// Thinking level: off (disabled), basic (4k tokens), medium (10k tokens), maximum (32k tokens). If not provided, determined by keywords in message.
	ThinkingLevel optionalnullable.OptionalNullable[ThinkingLevel] `json:"thinking_level,omitempty"`
}

func (s SendMessageRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SendMessageRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"text"}); err != nil {
		return err
	}
	return nil
}

func (s *SendMessageRequestBody) GetPlanMode() *bool {
	if s == nil {
		return nil
	}
	return s.PlanMode
}

func (s *SendMessageRequestBody) GetText() string {
	if s == nil {
		return ""
	}
	return s.Text
}

func (s *SendMessageRequestBody) GetThinkingLevel() optionalnullable.OptionalNullable[ThinkingLevel] {
	if s == nil {
		return nil
	}
	return s.ThinkingLevel
}

type SendMessageRequest struct {
	// Session ID
	ID          string                 `pathParam:"style=simple,explode=false,name=id"`
	RequestBody SendMessageRequestBody `request:"mediaType=application/json"`
}

func (s *SendMessageRequest) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SendMessageRequest) GetRequestBody() SendMessageRequestBody {
	if s == nil {
		return SendMessageRequestBody{}
	}
	return s.RequestBody
}

// SendMessageResponseBody - Message accepted for processing. Agent runs asynchronously and streams results via SSE.
type SendMessageResponseBody struct {
	// Session ID for the processing task
	SessionID string `json:"sessionId"`
	// Processing status
	Status string `json:"status"`
}

func (s *SendMessageResponseBody) GetSessionID() string {
	if s == nil {
		return ""
	}
	return s.SessionID
}

func (s *SendMessageResponseBody) GetStatus() string {
	if s == nil {
		return ""
	}
	return s.Status
}

type SendMessageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Message accepted for processing. Agent runs asynchronously and streams results via SSE.
	Object *SendMessageResponseBody
}

func (s *SendMessageResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SendMessageResponse) GetObject() *SendMessageResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
