// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type StartOAuthFlowRequest struct {
	// Provider name (currently only 'anthropic')
	Provider string `pathParam:"style=simple,explode=false,name=provider"`
}

func (s *StartOAuthFlowRequest) GetProvider() string {
	if s == nil {
		return ""
	}
	return s.Provider
}

// StartOAuthFlowResponseBody - OAuth authorization information
type StartOAuthFlowResponseBody struct {
	// OAuth authorization URL to redirect to
	AuthURL *string `json:"auth_url,omitempty"`
	// Instructions for completing OAuth flow
	Message *string `json:"message,omitempty"`
	// OAuth state token for verification
	State *string `json:"state,omitempty"`
}

func (s *StartOAuthFlowResponseBody) GetAuthURL() *string {
	if s == nil {
		return nil
	}
	return s.AuthURL
}

func (s *StartOAuthFlowResponseBody) GetMessage() *string {
	if s == nil {
		return nil
	}
	return s.Message
}

func (s *StartOAuthFlowResponseBody) GetState() *string {
	if s == nil {
		return nil
	}
	return s.State
}

type StartOAuthFlowResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OAuth authorization information
	Object *StartOAuthFlowResponseBody
}

func (s *StartOAuthFlowResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StartOAuthFlowResponse) GetObject() *StartOAuthFlowResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
