// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/recreate-run/mix-go-sdk/models/components"
)

// Provider name (anthropic, openai, openrouter, gemini, brave)
type Provider string

const (
	ProviderAnthropic  Provider = "anthropic"
	ProviderOpenai     Provider = "openai"
	ProviderOpenrouter Provider = "openrouter"
	ProviderGemini     Provider = "gemini"
	ProviderBrave      Provider = "brave"
)

func (e Provider) ToPointer() *Provider {
	return &e
}
func (e *Provider) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "anthropic":
		fallthrough
	case "openai":
		fallthrough
	case "openrouter":
		fallthrough
	case "gemini":
		fallthrough
	case "brave":
		*e = Provider(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Provider: %v", v)
	}
}

type StoreAPIKeyRequest struct {
	// API key for authentication
	APIKey string `json:"api_key"`
	// Provider name (anthropic, openai, openrouter, gemini, brave)
	Provider Provider `json:"provider"`
}

func (s *StoreAPIKeyRequest) GetAPIKey() string {
	if s == nil {
		return ""
	}
	return s.APIKey
}

func (s *StoreAPIKeyRequest) GetProvider() Provider {
	if s == nil {
		return Provider("")
	}
	return s.Provider
}

// StoreAPIKeyResponseBody - API key stored status
type StoreAPIKeyResponseBody struct {
	// Success message
	Message *string `json:"message,omitempty"`
	// Provider name
	Provider *string `json:"provider,omitempty"`
	// Operation status (success)
	Status *string `json:"status,omitempty"`
}

func (s *StoreAPIKeyResponseBody) GetMessage() *string {
	if s == nil {
		return nil
	}
	return s.Message
}

func (s *StoreAPIKeyResponseBody) GetProvider() *string {
	if s == nil {
		return nil
	}
	return s.Provider
}

func (s *StoreAPIKeyResponseBody) GetStatus() *string {
	if s == nil {
		return nil
	}
	return s.Status
}

type StoreAPIKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// API key stored status
	Object *StoreAPIKeyResponseBody
}

func (s *StoreAPIKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StoreAPIKeyResponse) GetObject() *StoreAPIKeyResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
