// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
	"github.com/recreate-run/mix-go-sdk/types/stream"
)

type StreamEventsRequest struct {
	// Session ID to stream events for
	SessionID string `queryParam:"style=form,explode=true,name=sessionId"`
	// Last received event ID for reconnection and event replay
	LastEventID *string `header:"style=simple,explode=false,name=Last-Event-ID"`
}

func (s *StreamEventsRequest) GetSessionID() string {
	if s == nil {
		return ""
	}
	return s.SessionID
}

func (s *StreamEventsRequest) GetLastEventID() *string {
	if s == nil {
		return nil
	}
	return s.LastEventID
}

type StreamEventsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// SSE event stream
	SSEEventStream *stream.EventStream[components.SSEEventStream]
	Headers        map[string][]string
}

func (s *StreamEventsResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StreamEventsResponse) GetSSEEventStream() *stream.EventStream[components.SSEEventStream] {
	if s == nil {
		return nil
	}
	return s.SSEEventStream
}

func (s *StreamEventsResponse) GetHeaders() map[string][]string {
	if s == nil {
		return map[string][]string{}
	}
	return s.Headers
}
