// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type UpdateSessionCallbacksRequestBody struct {
	// Session-level callbacks that execute after tool completion. Environment variables available: CALLBACK_TOOL_RESULT, CALLBACK_TOOL_NAME, CALLBACK_TOOL_ID, CALLBACK_SESSION_ID
	Callbacks []components.Callback `json:"callbacks"`
}

func (u *UpdateSessionCallbacksRequestBody) GetCallbacks() []components.Callback {
	if u == nil {
		return []components.Callback{}
	}
	return u.Callbacks
}

type UpdateSessionCallbacksRequest struct {
	// Session ID to update
	ID          string                            `pathParam:"style=simple,explode=false,name=id"`
	RequestBody UpdateSessionCallbacksRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateSessionCallbacksRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateSessionCallbacksRequest) GetRequestBody() UpdateSessionCallbacksRequestBody {
	if u == nil {
		return UpdateSessionCallbacksRequestBody{}
	}
	return u.RequestBody
}

type UpdateSessionCallbacksResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Session callbacks updated successfully
	SessionData *components.SessionData
}

func (u *UpdateSessionCallbacksResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateSessionCallbacksResponse) GetSessionData() *components.SessionData {
	if u == nil {
		return nil
	}
	return u.SessionData
}
