// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type UpdatePreferencesRequest struct {
	// Maximum tokens for main agent responses
	MainAgentMaxTokens *int64 `json:"main_agent_max_tokens,omitempty"`
	// Main agent model ID
	MainAgentModel *string `json:"main_agent_model,omitempty"`
	// Reasoning effort setting for main agent
	MainAgentReasoningEffort *string `json:"main_agent_reasoning_effort,omitempty"`
	// Preferred AI provider (anthropic, openai, openrouter)
	PreferredProvider *string `json:"preferred_provider,omitempty"`
	// Maximum tokens for sub agent responses
	SubAgentMaxTokens *int64 `json:"sub_agent_max_tokens,omitempty"`
	// Sub agent model ID
	SubAgentModel *string `json:"sub_agent_model,omitempty"`
	// Reasoning effort setting for sub agent
	SubAgentReasoningEffort *string `json:"sub_agent_reasoning_effort,omitempty"`
}

func (u *UpdatePreferencesRequest) GetMainAgentMaxTokens() *int64 {
	if u == nil {
		return nil
	}
	return u.MainAgentMaxTokens
}

func (u *UpdatePreferencesRequest) GetMainAgentModel() *string {
	if u == nil {
		return nil
	}
	return u.MainAgentModel
}

func (u *UpdatePreferencesRequest) GetMainAgentReasoningEffort() *string {
	if u == nil {
		return nil
	}
	return u.MainAgentReasoningEffort
}

func (u *UpdatePreferencesRequest) GetPreferredProvider() *string {
	if u == nil {
		return nil
	}
	return u.PreferredProvider
}

func (u *UpdatePreferencesRequest) GetSubAgentMaxTokens() *int64 {
	if u == nil {
		return nil
	}
	return u.SubAgentMaxTokens
}

func (u *UpdatePreferencesRequest) GetSubAgentModel() *string {
	if u == nil {
		return nil
	}
	return u.SubAgentModel
}

func (u *UpdatePreferencesRequest) GetSubAgentReasoningEffort() *string {
	if u == nil {
		return nil
	}
	return u.SubAgentReasoningEffort
}

// UpdatePreferencesResponseBody - Updated preferences
type UpdatePreferencesResponseBody struct {
	// Creation timestamp
	CreatedAt *int64 `json:"created_at,omitempty"`
	// Maximum tokens for main agent
	MainAgentMaxTokens *int64 `json:"main_agent_max_tokens,omitempty"`
	// Main agent model ID
	MainAgentModel *string `json:"main_agent_model,omitempty"`
	// Reasoning effort for main agent
	MainAgentReasoningEffort *string `json:"main_agent_reasoning_effort,omitempty"`
	// Preferred AI provider
	PreferredProvider *string `json:"preferred_provider,omitempty"`
	// Maximum tokens for sub agent
	SubAgentMaxTokens *int64 `json:"sub_agent_max_tokens,omitempty"`
	// Sub agent model ID
	SubAgentModel *string `json:"sub_agent_model,omitempty"`
	// Reasoning effort for sub agent
	SubAgentReasoningEffort *string `json:"sub_agent_reasoning_effort,omitempty"`
	// Last update timestamp
	UpdatedAt *int64 `json:"updated_at,omitempty"`
}

func (u *UpdatePreferencesResponseBody) GetCreatedAt() *int64 {
	if u == nil {
		return nil
	}
	return u.CreatedAt
}

func (u *UpdatePreferencesResponseBody) GetMainAgentMaxTokens() *int64 {
	if u == nil {
		return nil
	}
	return u.MainAgentMaxTokens
}

func (u *UpdatePreferencesResponseBody) GetMainAgentModel() *string {
	if u == nil {
		return nil
	}
	return u.MainAgentModel
}

func (u *UpdatePreferencesResponseBody) GetMainAgentReasoningEffort() *string {
	if u == nil {
		return nil
	}
	return u.MainAgentReasoningEffort
}

func (u *UpdatePreferencesResponseBody) GetPreferredProvider() *string {
	if u == nil {
		return nil
	}
	return u.PreferredProvider
}

func (u *UpdatePreferencesResponseBody) GetSubAgentMaxTokens() *int64 {
	if u == nil {
		return nil
	}
	return u.SubAgentMaxTokens
}

func (u *UpdatePreferencesResponseBody) GetSubAgentModel() *string {
	if u == nil {
		return nil
	}
	return u.SubAgentModel
}

func (u *UpdatePreferencesResponseBody) GetSubAgentReasoningEffort() *string {
	if u == nil {
		return nil
	}
	return u.SubAgentReasoningEffort
}

func (u *UpdatePreferencesResponseBody) GetUpdatedAt() *int64 {
	if u == nil {
		return nil
	}
	return u.UpdatedAt
}

type UpdatePreferencesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Updated preferences
	Object *UpdatePreferencesResponseBody
}

func (u *UpdatePreferencesResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdatePreferencesResponse) GetObject() *UpdatePreferencesResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
