// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type File struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (f *File) GetFileName() string {
	if f == nil {
		return ""
	}
	return f.FileName
}

func (f *File) GetContent() any {
	if f == nil {
		return nil
	}
	return f.Content
}

type UploadSessionFileRequestBody struct {
	// File to upload
	File File `multipartForm:"file,name=file"`
}

func (u *UploadSessionFileRequestBody) GetFile() File {
	if u == nil {
		return File{}
	}
	return u.File
}

type UploadSessionFileRequest struct {
	// Session ID
	ID          string                       `pathParam:"style=simple,explode=false,name=id"`
	RequestBody UploadSessionFileRequestBody `request:"mediaType=multipart/form-data"`
}

func (u *UploadSessionFileRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UploadSessionFileRequest) GetRequestBody() UploadSessionFileRequestBody {
	if u == nil {
		return UploadSessionFileRequestBody{}
	}
	return u.RequestBody
}

type UploadSessionFileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// File uploaded successfully
	FileInfo *components.FileInfo
}

func (u *UploadSessionFileResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UploadSessionFileResponse) GetFileInfo() *components.FileInfo {
	if u == nil {
		return nil
	}
	return u.FileInfo
}
