// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/recreate-run/mix-go-sdk/models/components"
)

// ValidatePreferredProviderAuthMethod - Authentication method used
type ValidatePreferredProviderAuthMethod string

const (
	ValidatePreferredProviderAuthMethodOauth  ValidatePreferredProviderAuthMethod = "oauth"
	ValidatePreferredProviderAuthMethodAPIKey ValidatePreferredProviderAuthMethod = "api_key"
	ValidatePreferredProviderAuthMethodNone   ValidatePreferredProviderAuthMethod = "none"
)

func (e ValidatePreferredProviderAuthMethod) ToPointer() *ValidatePreferredProviderAuthMethod {
	return &e
}
func (e *ValidatePreferredProviderAuthMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "oauth":
		fallthrough
	case "api_key":
		fallthrough
	case "none":
		*e = ValidatePreferredProviderAuthMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ValidatePreferredProviderAuthMethod: %v", v)
	}
}

// ValidatePreferredProviderResponseBody - Preferred provider validation status
type ValidatePreferredProviderResponseBody struct {
	// Authentication method used
	AuthMethod *ValidatePreferredProviderAuthMethod `json:"auth_method,omitempty"`
	// Status message
	Message *string `json:"message,omitempty"`
	// Preferred provider name
	Provider *string `json:"provider,omitempty"`
	// Whether preferred provider is authenticated
	Valid *bool `json:"valid,omitempty"`
}

func (v *ValidatePreferredProviderResponseBody) GetAuthMethod() *ValidatePreferredProviderAuthMethod {
	if v == nil {
		return nil
	}
	return v.AuthMethod
}

func (v *ValidatePreferredProviderResponseBody) GetMessage() *string {
	if v == nil {
		return nil
	}
	return v.Message
}

func (v *ValidatePreferredProviderResponseBody) GetProvider() *string {
	if v == nil {
		return nil
	}
	return v.Provider
}

func (v *ValidatePreferredProviderResponseBody) GetValid() *bool {
	if v == nil {
		return nil
	}
	return v.Valid
}

type ValidatePreferredProviderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Preferred provider validation status
	Object *ValidatePreferredProviderResponseBody
}

func (v *ValidatePreferredProviderResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *ValidatePreferredProviderResponse) GetObject() *ValidatePreferredProviderResponseBody {
	if v == nil {
		return nil
	}
	return v.Object
}
