// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// CallbackResultDataCallbackType - Type of callback executed
type CallbackResultDataCallbackType string

const (
	CallbackResultDataCallbackTypeBashScript  CallbackResultDataCallbackType = "bash_script"
	CallbackResultDataCallbackTypeSubAgent    CallbackResultDataCallbackType = "sub_agent"
	CallbackResultDataCallbackTypeSendMessage CallbackResultDataCallbackType = "send_message"
)

func (e CallbackResultDataCallbackType) ToPointer() *CallbackResultDataCallbackType {
	return &e
}
func (e *CallbackResultDataCallbackType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "bash_script":
		fallthrough
	case "sub_agent":
		fallthrough
	case "send_message":
		*e = CallbackResultDataCallbackType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CallbackResultDataCallbackType: %v", v)
	}
}

// CallbackResultData - Callback execution result information
type CallbackResultData struct {
	// Human-readable name of the callback (optional)
	CallbackName *string `json:"callback_name,omitempty"`
	// Type of callback executed
	CallbackType CallbackResultDataCallbackType `json:"callback_type"`
	// Error message if callback failed (optional)
	Error *string `json:"error,omitempty"`
	// Whether this callback result is excluded from agent context (optional)
	ExcludeFromContext *bool `json:"exclude_from_context,omitempty"`
	// Exit code from bash callback (optional)
	ExitCode *int64 `json:"exit_code,omitempty"`
	// Standard error from bash callback (optional)
	Stderr *string `json:"stderr,omitempty"`
	// Standard output from bash callback (optional)
	Stdout *string `json:"stdout,omitempty"`
	// ID of spawned sub-agent session (optional)
	SubagentID *string `json:"subagent_id,omitempty"`
	// Result from sub-agent execution (optional)
	SubagentResult *string `json:"subagent_result,omitempty"`
	// Whether callback executed successfully
	Success bool `json:"success"`
	// ID of the tool call that triggered this callback
	ToolCallID string `json:"tool_call_id"`
	// Name of the tool that triggered callback
	ToolName string `json:"tool_name"`
}

func (c *CallbackResultData) GetCallbackName() *string {
	if c == nil {
		return nil
	}
	return c.CallbackName
}

func (c *CallbackResultData) GetCallbackType() CallbackResultDataCallbackType {
	if c == nil {
		return CallbackResultDataCallbackType("")
	}
	return c.CallbackType
}

func (c *CallbackResultData) GetError() *string {
	if c == nil {
		return nil
	}
	return c.Error
}

func (c *CallbackResultData) GetExcludeFromContext() *bool {
	if c == nil {
		return nil
	}
	return c.ExcludeFromContext
}

func (c *CallbackResultData) GetExitCode() *int64 {
	if c == nil {
		return nil
	}
	return c.ExitCode
}

func (c *CallbackResultData) GetStderr() *string {
	if c == nil {
		return nil
	}
	return c.Stderr
}

func (c *CallbackResultData) GetStdout() *string {
	if c == nil {
		return nil
	}
	return c.Stdout
}

func (c *CallbackResultData) GetSubagentID() *string {
	if c == nil {
		return nil
	}
	return c.SubagentID
}

func (c *CallbackResultData) GetSubagentResult() *string {
	if c == nil {
		return nil
	}
	return c.SubagentResult
}

func (c *CallbackResultData) GetSuccess() bool {
	if c == nil {
		return false
	}
	return c.Success
}

func (c *CallbackResultData) GetToolCallID() string {
	if c == nil {
		return ""
	}
	return c.ToolCallID
}

func (c *CallbackResultData) GetToolName() string {
	if c == nil {
		return ""
	}
	return c.ToolName
}
