// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/recreate-run/mix-go-sdk/internal/utils"
)

// CallbackType - Callback type: 'bash_script' for shell commands, 'sub_agent' for spawning sub-agents, 'send_message' for injecting messages
type CallbackType string

const (
	CallbackTypeBashScript  CallbackType = "bash_script"
	CallbackTypeSubAgent    CallbackType = "sub_agent"
	CallbackTypeSendMessage CallbackType = "send_message"
)

func (e CallbackType) ToPointer() *CallbackType {
	return &e
}
func (e *CallbackType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "bash_script":
		fallthrough
	case "sub_agent":
		fallthrough
	case "send_message":
		*e = CallbackType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CallbackType: %v", v)
	}
}

// Callback - Session-level callback configuration that executes after tool completion
type Callback struct {
	// Bash command to execute (required for bash_script type). Has access to environment variables.
	BashCommand *string `json:"bashCommand,omitempty"`
	// Timeout in milliseconds for bash execution (default: 120000)
	BashTimeout *int64 `default:"120000" json:"bashTimeout"`
	// Exclude callback results from agent context. Only applies to bash_script and sub_agent types. Not allowed for send_message.
	ExcludeFromContext *bool `default:"false" json:"excludeFromContext"`
	// Include full conversation history in sub-agent context (not yet implemented)
	IncludeFullHistory *bool `default:"false" json:"includeFullHistory"`
	// Message content to inject into the conversation (required for send_message type). Will be sent as a User message.
	MessageContent *string `json:"messageContent,omitempty"`
	// Human-readable name for this callback (optional, defaults to 'Callback #XXXX')
	Name *string `json:"name,omitempty"`
	// Prompt for the sub-agent (required for sub_agent type). Tool execution context is automatically appended.
	SubAgentPrompt *string `json:"subAgentPrompt,omitempty"`
	// Type of sub-agent to spawn (default: 'general-purpose')
	SubAgentType *string `default:"general-purpose" json:"subAgentType"`
	// Tool to attach callback to (e.g., 'show', 'bash', '*' for all tools)
	ToolName string `json:"toolName"`
	// Callback type: 'bash_script' for shell commands, 'sub_agent' for spawning sub-agents, 'send_message' for injecting messages
	Type CallbackType `json:"type"`
}

func (c Callback) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Callback) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Callback) GetBashCommand() *string {
	if c == nil {
		return nil
	}
	return c.BashCommand
}

func (c *Callback) GetBashTimeout() *int64 {
	if c == nil {
		return nil
	}
	return c.BashTimeout
}

func (c *Callback) GetExcludeFromContext() *bool {
	if c == nil {
		return nil
	}
	return c.ExcludeFromContext
}

func (c *Callback) GetIncludeFullHistory() *bool {
	if c == nil {
		return nil
	}
	return c.IncludeFullHistory
}

func (c *Callback) GetMessageContent() *string {
	if c == nil {
		return nil
	}
	return c.MessageContent
}

func (c *Callback) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *Callback) GetSubAgentPrompt() *string {
	if c == nil {
		return nil
	}
	return c.SubAgentPrompt
}

func (c *Callback) GetSubAgentType() *string {
	if c == nil {
		return nil
	}
	return c.SubAgentType
}

func (c *Callback) GetToolName() string {
	if c == nil {
		return ""
	}
	return c.ToolName
}

func (c *Callback) GetType() CallbackType {
	if c == nil {
		return CallbackType("")
	}
	return c.Type
}
