// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// CoreToolName - Core built-in tool names
type CoreToolName string

const (
	CoreToolNameBash            CoreToolName = "Bash"
	CoreToolNameReadText        CoreToolName = "ReadText"
	CoreToolNameGlob            CoreToolName = "Glob"
	CoreToolNameReadMedia       CoreToolName = "ReadMedia"
	CoreToolNameGrep            CoreToolName = "Grep"
	CoreToolNameWrite           CoreToolName = "Write"
	CoreToolNameEdit            CoreToolName = "Edit"
	CoreToolNamePythonExecution CoreToolName = "python_execution"
	CoreToolNameSearch          CoreToolName = "Search"
	CoreToolNameTodoWrite       CoreToolName = "TodoWrite"
	CoreToolNameExitPlanMode    CoreToolName = "ExitPlanMode"
	CoreToolNameShowMedia       CoreToolName = "ShowMedia"
	CoreToolNameTask            CoreToolName = "Task"
)

func (e CoreToolName) ToPointer() *CoreToolName {
	return &e
}
func (e *CoreToolName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Bash":
		fallthrough
	case "ReadText":
		fallthrough
	case "Glob":
		fallthrough
	case "ReadMedia":
		fallthrough
	case "Grep":
		fallthrough
	case "Write":
		fallthrough
	case "Edit":
		fallthrough
	case "python_execution":
		fallthrough
	case "Search":
		fallthrough
	case "TodoWrite":
		fallthrough
	case "ExitPlanMode":
		fallthrough
	case "ShowMedia":
		fallthrough
	case "Task":
		*e = CoreToolName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CoreToolName: %v", v)
	}
}
