// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// InputJSON - Parsed tool input (optional)
type InputJSON struct {
}

// ExportToolCall - Complete tool call information for export
type ExportToolCall struct {
	// Whether tool execution finished
	Finished bool `json:"finished"`
	// Tool call identifier
	ID string `json:"id"`
	// Tool input as JSON string
	Input string `json:"input"`
	// Parsed tool input (optional)
	InputJSON *InputJSON `json:"inputJson,omitempty"`
	// Whether execution resulted in error (optional)
	IsError *bool `json:"isError,omitempty"`
	// Additional tool metadata (optional)
	Metadata *string `json:"metadata,omitempty"`
	// Tool name
	Name string `json:"name"`
	// Tool execution result (optional)
	Result *string `json:"result,omitempty"`
	// Tool type
	Type string `json:"type"`
}

func (e *ExportToolCall) GetFinished() bool {
	if e == nil {
		return false
	}
	return e.Finished
}

func (e *ExportToolCall) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *ExportToolCall) GetInput() string {
	if e == nil {
		return ""
	}
	return e.Input
}

func (e *ExportToolCall) GetInputJSON() *InputJSON {
	if e == nil {
		return nil
	}
	return e.InputJSON
}

func (e *ExportToolCall) GetIsError() *bool {
	if e == nil {
		return nil
	}
	return e.IsError
}

func (e *ExportToolCall) GetMetadata() *string {
	if e == nil {
		return nil
	}
	return e.Metadata
}

func (e *ExportToolCall) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *ExportToolCall) GetResult() *string {
	if e == nil {
		return nil
	}
	return e.Result
}

func (e *ExportToolCall) GetType() string {
	if e == nil {
		return ""
	}
	return e.Type
}
