// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/recreate-run/mix-go-sdk/internal/utils"
	"time"
)

// ExportMessage - Complete message information for export
type ExportMessage struct {
	// Message content
	Content string `json:"content"`
	// Message creation timestamp
	CreatedAt time.Time `json:"createdAt"`
	// Completion finish reason (optional)
	FinishReason *string `json:"finishReason,omitempty"`
	// Message identifier
	ID string `json:"id"`
	// Model used for this message (optional)
	Model *string `json:"model,omitempty"`
	// Reasoning content (optional)
	Reasoning *string `json:"reasoning,omitempty"`
	// Reasoning duration in milliseconds (optional)
	ReasoningDuration *int64 `json:"reasoningDuration,omitempty"`
	// Message role (user, assistant, tool)
	Role string `json:"role"`
	// Tool calls with complete information
	ToolCalls []ExportToolCall `json:"toolCalls,omitempty"`
	// Message update timestamp
	UpdatedAt time.Time `json:"updatedAt"`
}

func (e ExportMessage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExportMessage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"content", "createdAt", "id", "role", "updatedAt"}); err != nil {
		return err
	}
	return nil
}

func (e *ExportMessage) GetContent() string {
	if e == nil {
		return ""
	}
	return e.Content
}

func (e *ExportMessage) GetCreatedAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.CreatedAt
}

func (e *ExportMessage) GetFinishReason() *string {
	if e == nil {
		return nil
	}
	return e.FinishReason
}

func (e *ExportMessage) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *ExportMessage) GetModel() *string {
	if e == nil {
		return nil
	}
	return e.Model
}

func (e *ExportMessage) GetReasoning() *string {
	if e == nil {
		return nil
	}
	return e.Reasoning
}

func (e *ExportMessage) GetReasoningDuration() *int64 {
	if e == nil {
		return nil
	}
	return e.ReasoningDuration
}

func (e *ExportMessage) GetRole() string {
	if e == nil {
		return ""
	}
	return e.Role
}

func (e *ExportMessage) GetToolCalls() []ExportToolCall {
	if e == nil {
		return nil
	}
	return e.ToolCalls
}

func (e *ExportMessage) GetUpdatedAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.UpdatedAt
}
