// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/recreate-run/mix-go-sdk/internal/utils"
	"time"
)

// ExportSession - Comprehensive session export with all messages, tool calls, and metadata
type ExportSession struct {
	// Number of assistant messages
	AssistantMessageCount *int64 `json:"assistantMessageCount,omitempty"`
	// Total completion tokens used
	CompletionTokens *int64 `json:"completionTokens,omitempty"`
	// Total cost of session
	Cost *float64 `json:"cost,omitempty"`
	// Session creation timestamp
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Session identifier
	ID string `json:"id"`
	// Complete list of messages with full details
	Messages []ExportMessage `json:"messages"`
	// Total prompt tokens used
	PromptTokens *int64 `json:"promptTokens,omitempty"`
	// Session title
	Title string `json:"title"`
	// Total number of tool calls
	ToolCallCount *int64 `json:"toolCallCount,omitempty"`
	// Session last update timestamp
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Number of user messages
	UserMessageCount *int64 `json:"userMessageCount,omitempty"`
}

func (e ExportSession) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExportSession) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"id", "messages", "title"}); err != nil {
		return err
	}
	return nil
}

func (e *ExportSession) GetAssistantMessageCount() *int64 {
	if e == nil {
		return nil
	}
	return e.AssistantMessageCount
}

func (e *ExportSession) GetCompletionTokens() *int64 {
	if e == nil {
		return nil
	}
	return e.CompletionTokens
}

func (e *ExportSession) GetCost() *float64 {
	if e == nil {
		return nil
	}
	return e.Cost
}

func (e *ExportSession) GetCreatedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.CreatedAt
}

func (e *ExportSession) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *ExportSession) GetMessages() []ExportMessage {
	if e == nil {
		return []ExportMessage{}
	}
	return e.Messages
}

func (e *ExportSession) GetPromptTokens() *int64 {
	if e == nil {
		return nil
	}
	return e.PromptTokens
}

func (e *ExportSession) GetTitle() string {
	if e == nil {
		return ""
	}
	return e.Title
}

func (e *ExportSession) GetToolCallCount() *int64 {
	if e == nil {
		return nil
	}
	return e.ToolCallCount
}

func (e *ExportSession) GetUpdatedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.UpdatedAt
}

func (e *ExportSession) GetUserMessageCount() *int64 {
	if e == nil {
		return nil
	}
	return e.UserMessageCount
}
