// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FileInfo struct {
	// Whether this is a directory
	IsDir bool `json:"isDir"`
	// Last modified timestamp (Unix time)
	Modified int64 `json:"modified"`
	// File name
	Name string `json:"name"`
	// File size in bytes
	Size int64 `json:"size"`
	// Static URL to access the file
	URL string `json:"url"`
}

func (f *FileInfo) GetIsDir() bool {
	if f == nil {
		return false
	}
	return f.IsDir
}

func (f *FileInfo) GetModified() int64 {
	if f == nil {
		return 0
	}
	return f.Modified
}

func (f *FileInfo) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *FileInfo) GetSize() int64 {
	if f == nil {
		return 0
	}
	return f.Size
}

func (f *FileInfo) GetURL() string {
	if f == nil {
		return ""
	}
	return f.URL
}
