// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// RESTErrorType - Error type
type RESTErrorType string

const (
	RESTErrorTypeBadRequest      RESTErrorType = "bad_request"
	RESTErrorTypeNotFound        RESTErrorType = "not_found"
	RESTErrorTypeInternalError   RESTErrorType = "internal_error"
	RESTErrorTypeUnauthorized    RESTErrorType = "unauthorized"
	RESTErrorTypeValidationError RESTErrorType = "validation_error"
)

func (e RESTErrorType) ToPointer() *RESTErrorType {
	return &e
}
func (e *RESTErrorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "bad_request":
		fallthrough
	case "not_found":
		fallthrough
	case "internal_error":
		fallthrough
	case "unauthorized":
		fallthrough
	case "validation_error":
		*e = RESTErrorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RESTErrorType: %v", v)
	}
}

type RESTError struct {
	// HTTP status code
	Code int64 `json:"code"`
	// Error message
	Message string `json:"message"`
	// Error type
	Type RESTErrorType `json:"type"`
}

func (r *RESTError) GetCode() int64 {
	if r == nil {
		return 0
	}
	return r.Code
}

func (r *RESTError) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

func (r *RESTError) GetType() RESTErrorType {
	if r == nil {
		return RESTErrorType("")
	}
	return r.Type
}
