// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/recreate-run/mix-go-sdk/internal/utils"
	"time"
)

// SessionType - Session type:
// - 'main': Root-level user interactions
// - 'subagent': Delegated task workers
type SessionType string

const (
	SessionTypeMain     SessionType = "main"
	SessionTypeSubagent SessionType = "subagent"
)

func (e SessionType) ToPointer() *SessionType {
	return &e
}
func (e *SessionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "main":
		fallthrough
	case "subagent":
		*e = SessionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SessionType: %v", v)
	}
}

// SubagentType - Subagent specialization type (only present for subagent sessions)
type SubagentType string

const (
	SubagentTypeGeneralPurpose SubagentType = "general-purpose"
)

func (e SubagentType) ToPointer() *SubagentType {
	return &e
}
func (e *SubagentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "general-purpose":
		*e = SubagentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SubagentType: %v", v)
	}
}

type SessionData struct {
	// Number of assistant messages in session
	AssistantMessageCount int64 `json:"assistantMessageCount"`
	// Session-level callback configurations (optional)
	Callbacks []Callback `json:"callbacks,omitempty"`
	// Total completion tokens used
	CompletionTokens int64 `json:"completionTokens"`
	// Total cost of session (for subagent sessions, costs are also accumulated in parent session)
	Cost float64 `json:"cost"`
	// Session creation timestamp
	CreatedAt time.Time `json:"createdAt"`
	// First user message (optional)
	FirstUserMessage *string `json:"firstUserMessage,omitempty"`
	// Unique session identifier
	ID string `json:"id"`
	// Parent session ID for subagent sessions (null for main sessions)
	ParentSessionID *string `json:"parentSessionId,omitempty"`
	// ID of the tool call that spawned this subagent session (null for non-subagent sessions)
	ParentToolCallID *string `json:"parentToolCallId,omitempty"`
	// Total prompt tokens used
	PromptTokens int64 `json:"promptTokens"`
	// Session type:
	// - 'main': Root-level user interactions
	// - 'subagent': Delegated task workers
	SessionType SessionType `json:"sessionType"`
	// Subagent specialization type (only present for subagent sessions)
	SubagentType *SubagentType `json:"subagentType,omitempty"`
	// Session title
	Title string `json:"title"`
	// Number of tool calls made in session
	ToolCallCount int64 `json:"toolCallCount"`
	// Number of user messages in session
	UserMessageCount int64 `json:"userMessageCount"`
}

func (s SessionData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SessionData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"assistantMessageCount", "completionTokens", "cost", "createdAt", "id", "promptTokens", "sessionType", "title", "toolCallCount", "userMessageCount"}); err != nil {
		return err
	}
	return nil
}

func (s *SessionData) GetAssistantMessageCount() int64 {
	if s == nil {
		return 0
	}
	return s.AssistantMessageCount
}

func (s *SessionData) GetCallbacks() []Callback {
	if s == nil {
		return nil
	}
	return s.Callbacks
}

func (s *SessionData) GetCompletionTokens() int64 {
	if s == nil {
		return 0
	}
	return s.CompletionTokens
}

func (s *SessionData) GetCost() float64 {
	if s == nil {
		return 0.0
	}
	return s.Cost
}

func (s *SessionData) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *SessionData) GetFirstUserMessage() *string {
	if s == nil {
		return nil
	}
	return s.FirstUserMessage
}

func (s *SessionData) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SessionData) GetParentSessionID() *string {
	if s == nil {
		return nil
	}
	return s.ParentSessionID
}

func (s *SessionData) GetParentToolCallID() *string {
	if s == nil {
		return nil
	}
	return s.ParentToolCallID
}

func (s *SessionData) GetPromptTokens() int64 {
	if s == nil {
		return 0
	}
	return s.PromptTokens
}

func (s *SessionData) GetSessionType() SessionType {
	if s == nil {
		return SessionType("")
	}
	return s.SessionType
}

func (s *SessionData) GetSubagentType() *SubagentType {
	if s == nil {
		return nil
	}
	return s.SubagentType
}

func (s *SessionData) GetTitle() string {
	if s == nil {
		return ""
	}
	return s.Title
}

func (s *SessionData) GetToolCallCount() int64 {
	if s == nil {
		return 0
	}
	return s.ToolCallCount
}

func (s *SessionData) GetUserMessageCount() int64 {
	if s == nil {
		return 0
	}
	return s.UserMessageCount
}
