// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/recreate-run/mix-go-sdk/internal/utils"
)

// SSESessionDeletedEventEvent - Event type identifier
type SSESessionDeletedEventEvent string

const (
	SSESessionDeletedEventEventConnected                         SSESessionDeletedEventEvent = "connected"
	SSESessionDeletedEventEventHeartbeat                         SSESessionDeletedEventEvent = "heartbeat"
	SSESessionDeletedEventEventError                             SSESessionDeletedEventEvent = "error"
	SSESessionDeletedEventEventComplete                          SSESessionDeletedEventEvent = "complete"
	SSESessionDeletedEventEventThinking                          SSESessionDeletedEventEvent = "thinking"
	SSESessionDeletedEventEventContent                           SSESessionDeletedEventEvent = "content"
	SSESessionDeletedEventEventToolUseStart                      SSESessionDeletedEventEvent = "tool_use_start"
	SSESessionDeletedEventEventToolUseParameterStreamingComplete SSESessionDeletedEventEvent = "tool_use_parameter_streaming_complete"
	SSESessionDeletedEventEventToolUseParameterDelta             SSESessionDeletedEventEvent = "tool_use_parameter_delta"
	SSESessionDeletedEventEventToolExecutionStart                SSESessionDeletedEventEvent = "tool_execution_start"
	SSESessionDeletedEventEventToolExecutionComplete             SSESessionDeletedEventEvent = "tool_execution_complete"
	SSESessionDeletedEventEventPermission                        SSESessionDeletedEventEvent = "permission"
	SSESessionDeletedEventEventUserMessageCreated                SSESessionDeletedEventEvent = "user_message_created"
	SSESessionDeletedEventEventSessionCreated                    SSESessionDeletedEventEvent = "session_created"
	SSESessionDeletedEventEventSessionDeleted                    SSESessionDeletedEventEvent = "session_deleted"
)

func (e SSESessionDeletedEventEvent) ToPointer() *SSESessionDeletedEventEvent {
	return &e
}
func (e *SSESessionDeletedEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "connected":
		fallthrough
	case "heartbeat":
		fallthrough
	case "error":
		fallthrough
	case "complete":
		fallthrough
	case "thinking":
		fallthrough
	case "content":
		fallthrough
	case "tool_use_start":
		fallthrough
	case "tool_use_parameter_streaming_complete":
		fallthrough
	case "tool_use_parameter_delta":
		fallthrough
	case "tool_execution_start":
		fallthrough
	case "tool_execution_complete":
		fallthrough
	case "permission":
		fallthrough
	case "user_message_created":
		fallthrough
	case "session_created":
		fallthrough
	case "session_deleted":
		*e = SSESessionDeletedEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SSESessionDeletedEventEvent: %v", v)
	}
}

type SSESessionDeletedEventData struct {
	// ID of the deleted session
	SessionID string `json:"sessionId"`
	// Event type
	Type string `json:"type"`
}

func (s SSESessionDeletedEventData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSESessionDeletedEventData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"sessionId", "type"}); err != nil {
		return err
	}
	return nil
}

func (s *SSESessionDeletedEventData) GetSessionID() string {
	if s == nil {
		return ""
	}
	return s.SessionID
}

func (s *SSESessionDeletedEventData) GetType() string {
	if s == nil {
		return ""
	}
	return s.Type
}

// SSESessionDeletedEvent - Base SSE event with standard fields
type SSESessionDeletedEvent struct {
	// Event type identifier
	Event SSESessionDeletedEventEvent `json:"event"`
	// Unique sequential event identifier for ordering and reconnection
	ID string `json:"id"`
	// Client retry interval in milliseconds
	Retry *int64                     `json:"retry,omitempty"`
	Data  SSESessionDeletedEventData `json:"data"`
}

func (s SSESessionDeletedEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSESessionDeletedEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"event", "id", "data"}); err != nil {
		return err
	}
	return nil
}

func (s *SSESessionDeletedEvent) GetEvent() SSESessionDeletedEventEvent {
	if s == nil {
		return SSESessionDeletedEventEvent("")
	}
	return s.Event
}

func (s *SSESessionDeletedEvent) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSESessionDeletedEvent) GetRetry() *int64 {
	if s == nil {
		return nil
	}
	return s.Retry
}

func (s *SSESessionDeletedEvent) GetData() SSESessionDeletedEventData {
	if s == nil {
		return SSESessionDeletedEventData{}
	}
	return s.Data
}

// SSESessionCreatedEventEvent - Event type identifier
type SSESessionCreatedEventEvent string

const (
	SSESessionCreatedEventEventConnected                         SSESessionCreatedEventEvent = "connected"
	SSESessionCreatedEventEventHeartbeat                         SSESessionCreatedEventEvent = "heartbeat"
	SSESessionCreatedEventEventError                             SSESessionCreatedEventEvent = "error"
	SSESessionCreatedEventEventComplete                          SSESessionCreatedEventEvent = "complete"
	SSESessionCreatedEventEventThinking                          SSESessionCreatedEventEvent = "thinking"
	SSESessionCreatedEventEventContent                           SSESessionCreatedEventEvent = "content"
	SSESessionCreatedEventEventToolUseStart                      SSESessionCreatedEventEvent = "tool_use_start"
	SSESessionCreatedEventEventToolUseParameterStreamingComplete SSESessionCreatedEventEvent = "tool_use_parameter_streaming_complete"
	SSESessionCreatedEventEventToolUseParameterDelta             SSESessionCreatedEventEvent = "tool_use_parameter_delta"
	SSESessionCreatedEventEventToolExecutionStart                SSESessionCreatedEventEvent = "tool_execution_start"
	SSESessionCreatedEventEventToolExecutionComplete             SSESessionCreatedEventEvent = "tool_execution_complete"
	SSESessionCreatedEventEventPermission                        SSESessionCreatedEventEvent = "permission"
	SSESessionCreatedEventEventUserMessageCreated                SSESessionCreatedEventEvent = "user_message_created"
	SSESessionCreatedEventEventSessionCreated                    SSESessionCreatedEventEvent = "session_created"
	SSESessionCreatedEventEventSessionDeleted                    SSESessionCreatedEventEvent = "session_deleted"
)

func (e SSESessionCreatedEventEvent) ToPointer() *SSESessionCreatedEventEvent {
	return &e
}
func (e *SSESessionCreatedEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "connected":
		fallthrough
	case "heartbeat":
		fallthrough
	case "error":
		fallthrough
	case "complete":
		fallthrough
	case "thinking":
		fallthrough
	case "content":
		fallthrough
	case "tool_use_start":
		fallthrough
	case "tool_use_parameter_streaming_complete":
		fallthrough
	case "tool_use_parameter_delta":
		fallthrough
	case "tool_execution_start":
		fallthrough
	case "tool_execution_complete":
		fallthrough
	case "permission":
		fallthrough
	case "user_message_created":
		fallthrough
	case "session_created":
		fallthrough
	case "session_deleted":
		*e = SSESessionCreatedEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SSESessionCreatedEventEvent: %v", v)
	}
}

type SSESessionCreatedEventData struct {
	// Unix timestamp when the session was created
	CreatedAt int64 `json:"createdAt"`
	// ID of the newly created session
	SessionID string `json:"sessionId"`
	// Title of the newly created session
	Title string `json:"title"`
	// Event type
	Type string `json:"type"`
}

func (s SSESessionCreatedEventData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSESessionCreatedEventData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"createdAt", "sessionId", "title", "type"}); err != nil {
		return err
	}
	return nil
}

func (s *SSESessionCreatedEventData) GetCreatedAt() int64 {
	if s == nil {
		return 0
	}
	return s.CreatedAt
}

func (s *SSESessionCreatedEventData) GetSessionID() string {
	if s == nil {
		return ""
	}
	return s.SessionID
}

func (s *SSESessionCreatedEventData) GetTitle() string {
	if s == nil {
		return ""
	}
	return s.Title
}

func (s *SSESessionCreatedEventData) GetType() string {
	if s == nil {
		return ""
	}
	return s.Type
}

// SSESessionCreatedEvent - Base SSE event with standard fields
type SSESessionCreatedEvent struct {
	// Event type identifier
	Event SSESessionCreatedEventEvent `json:"event"`
	// Unique sequential event identifier for ordering and reconnection
	ID string `json:"id"`
	// Client retry interval in milliseconds
	Retry *int64                     `json:"retry,omitempty"`
	Data  SSESessionCreatedEventData `json:"data"`
}

func (s SSESessionCreatedEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSESessionCreatedEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"event", "id", "data"}); err != nil {
		return err
	}
	return nil
}

func (s *SSESessionCreatedEvent) GetEvent() SSESessionCreatedEventEvent {
	if s == nil {
		return SSESessionCreatedEventEvent("")
	}
	return s.Event
}

func (s *SSESessionCreatedEvent) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSESessionCreatedEvent) GetRetry() *int64 {
	if s == nil {
		return nil
	}
	return s.Retry
}

func (s *SSESessionCreatedEvent) GetData() SSESessionCreatedEventData {
	if s == nil {
		return SSESessionCreatedEventData{}
	}
	return s.Data
}

// SSEUserMessageCreatedEventEvent - Event type identifier
type SSEUserMessageCreatedEventEvent string

const (
	SSEUserMessageCreatedEventEventConnected                         SSEUserMessageCreatedEventEvent = "connected"
	SSEUserMessageCreatedEventEventHeartbeat                         SSEUserMessageCreatedEventEvent = "heartbeat"
	SSEUserMessageCreatedEventEventError                             SSEUserMessageCreatedEventEvent = "error"
	SSEUserMessageCreatedEventEventComplete                          SSEUserMessageCreatedEventEvent = "complete"
	SSEUserMessageCreatedEventEventThinking                          SSEUserMessageCreatedEventEvent = "thinking"
	SSEUserMessageCreatedEventEventContent                           SSEUserMessageCreatedEventEvent = "content"
	SSEUserMessageCreatedEventEventToolUseStart                      SSEUserMessageCreatedEventEvent = "tool_use_start"
	SSEUserMessageCreatedEventEventToolUseParameterStreamingComplete SSEUserMessageCreatedEventEvent = "tool_use_parameter_streaming_complete"
	SSEUserMessageCreatedEventEventToolUseParameterDelta             SSEUserMessageCreatedEventEvent = "tool_use_parameter_delta"
	SSEUserMessageCreatedEventEventToolExecutionStart                SSEUserMessageCreatedEventEvent = "tool_execution_start"
	SSEUserMessageCreatedEventEventToolExecutionComplete             SSEUserMessageCreatedEventEvent = "tool_execution_complete"
	SSEUserMessageCreatedEventEventPermission                        SSEUserMessageCreatedEventEvent = "permission"
	SSEUserMessageCreatedEventEventUserMessageCreated                SSEUserMessageCreatedEventEvent = "user_message_created"
	SSEUserMessageCreatedEventEventSessionCreated                    SSEUserMessageCreatedEventEvent = "session_created"
	SSEUserMessageCreatedEventEventSessionDeleted                    SSEUserMessageCreatedEventEvent = "session_deleted"
)

func (e SSEUserMessageCreatedEventEvent) ToPointer() *SSEUserMessageCreatedEventEvent {
	return &e
}
func (e *SSEUserMessageCreatedEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "connected":
		fallthrough
	case "heartbeat":
		fallthrough
	case "error":
		fallthrough
	case "complete":
		fallthrough
	case "thinking":
		fallthrough
	case "content":
		fallthrough
	case "tool_use_start":
		fallthrough
	case "tool_use_parameter_streaming_complete":
		fallthrough
	case "tool_use_parameter_delta":
		fallthrough
	case "tool_execution_start":
		fallthrough
	case "tool_execution_complete":
		fallthrough
	case "permission":
		fallthrough
	case "user_message_created":
		fallthrough
	case "session_created":
		fallthrough
	case "session_deleted":
		*e = SSEUserMessageCreatedEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SSEUserMessageCreatedEventEvent: %v", v)
	}
}

type SSEUserMessageCreatedEventData struct {
	// Content of the user message
	Content string `json:"content"`
	// ID of the created user message
	MessageID string `json:"messageId"`
	// ID of the parent tool call that spawned this subagent (for nested events)
	ParentToolCallID *string `json:"parentToolCallId,omitempty"`
	// User message created event type
	Type string `json:"type"`
}

func (s SSEUserMessageCreatedEventData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEUserMessageCreatedEventData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"content", "messageId", "type"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEUserMessageCreatedEventData) GetContent() string {
	if s == nil {
		return ""
	}
	return s.Content
}

func (s *SSEUserMessageCreatedEventData) GetMessageID() string {
	if s == nil {
		return ""
	}
	return s.MessageID
}

func (s *SSEUserMessageCreatedEventData) GetParentToolCallID() *string {
	if s == nil {
		return nil
	}
	return s.ParentToolCallID
}

func (s *SSEUserMessageCreatedEventData) GetType() string {
	if s == nil {
		return ""
	}
	return s.Type
}

// SSEUserMessageCreatedEvent - Base SSE event with standard fields
type SSEUserMessageCreatedEvent struct {
	// Event type identifier
	Event SSEUserMessageCreatedEventEvent `json:"event"`
	// Unique sequential event identifier for ordering and reconnection
	ID string `json:"id"`
	// Client retry interval in milliseconds
	Retry *int64                         `json:"retry,omitempty"`
	Data  SSEUserMessageCreatedEventData `json:"data"`
}

func (s SSEUserMessageCreatedEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEUserMessageCreatedEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"event", "id", "data"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEUserMessageCreatedEvent) GetEvent() SSEUserMessageCreatedEventEvent {
	if s == nil {
		return SSEUserMessageCreatedEventEvent("")
	}
	return s.Event
}

func (s *SSEUserMessageCreatedEvent) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSEUserMessageCreatedEvent) GetRetry() *int64 {
	if s == nil {
		return nil
	}
	return s.Retry
}

func (s *SSEUserMessageCreatedEvent) GetData() SSEUserMessageCreatedEventData {
	if s == nil {
		return SSEUserMessageCreatedEventData{}
	}
	return s.Data
}

// SSEPermissionEventEvent - Event type identifier
type SSEPermissionEventEvent string

const (
	SSEPermissionEventEventConnected                         SSEPermissionEventEvent = "connected"
	SSEPermissionEventEventHeartbeat                         SSEPermissionEventEvent = "heartbeat"
	SSEPermissionEventEventError                             SSEPermissionEventEvent = "error"
	SSEPermissionEventEventComplete                          SSEPermissionEventEvent = "complete"
	SSEPermissionEventEventThinking                          SSEPermissionEventEvent = "thinking"
	SSEPermissionEventEventContent                           SSEPermissionEventEvent = "content"
	SSEPermissionEventEventToolUseStart                      SSEPermissionEventEvent = "tool_use_start"
	SSEPermissionEventEventToolUseParameterStreamingComplete SSEPermissionEventEvent = "tool_use_parameter_streaming_complete"
	SSEPermissionEventEventToolUseParameterDelta             SSEPermissionEventEvent = "tool_use_parameter_delta"
	SSEPermissionEventEventToolExecutionStart                SSEPermissionEventEvent = "tool_execution_start"
	SSEPermissionEventEventToolExecutionComplete             SSEPermissionEventEvent = "tool_execution_complete"
	SSEPermissionEventEventPermission                        SSEPermissionEventEvent = "permission"
	SSEPermissionEventEventUserMessageCreated                SSEPermissionEventEvent = "user_message_created"
	SSEPermissionEventEventSessionCreated                    SSEPermissionEventEvent = "session_created"
	SSEPermissionEventEventSessionDeleted                    SSEPermissionEventEvent = "session_deleted"
)

func (e SSEPermissionEventEvent) ToPointer() *SSEPermissionEventEvent {
	return &e
}
func (e *SSEPermissionEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "connected":
		fallthrough
	case "heartbeat":
		fallthrough
	case "error":
		fallthrough
	case "complete":
		fallthrough
	case "thinking":
		fallthrough
	case "content":
		fallthrough
	case "tool_use_start":
		fallthrough
	case "tool_use_parameter_streaming_complete":
		fallthrough
	case "tool_use_parameter_delta":
		fallthrough
	case "tool_execution_start":
		fallthrough
	case "tool_execution_complete":
		fallthrough
	case "permission":
		fallthrough
	case "user_message_created":
		fallthrough
	case "session_created":
		fallthrough
	case "session_deleted":
		*e = SSEPermissionEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SSEPermissionEventEvent: %v", v)
	}
}

// Params - Additional parameters for the permission request
type Params struct {
}

func (p Params) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Params) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

type SSEPermissionEventData struct {
	// Requested action description
	Action string `json:"action"`
	// Human-readable permission description
	Description string `json:"description"`
	// Permission request identifier
	ID string `json:"id"`
	// Additional parameters for the permission request
	Params *Params `json:"params,omitempty"`
	// ID of the parent tool call that spawned this subagent (for nested events)
	ParentToolCallID *string `json:"parentToolCallId,omitempty"`
	// File path for permission request
	Path *string `json:"path,omitempty"`
	// Session identifier for the permission request
	SessionID string `json:"sessionId"`
	// Tool name - either a core tool or MCP tool following {serverName}_{toolName} pattern
	ToolName ToolName `json:"toolName"`
	// Permission event type
	Type string `json:"type"`
}

func (s SSEPermissionEventData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEPermissionEventData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"action", "description", "id", "sessionId", "toolName", "type"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEPermissionEventData) GetAction() string {
	if s == nil {
		return ""
	}
	return s.Action
}

func (s *SSEPermissionEventData) GetDescription() string {
	if s == nil {
		return ""
	}
	return s.Description
}

func (s *SSEPermissionEventData) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSEPermissionEventData) GetParams() *Params {
	if s == nil {
		return nil
	}
	return s.Params
}

func (s *SSEPermissionEventData) GetParentToolCallID() *string {
	if s == nil {
		return nil
	}
	return s.ParentToolCallID
}

func (s *SSEPermissionEventData) GetPath() *string {
	if s == nil {
		return nil
	}
	return s.Path
}

func (s *SSEPermissionEventData) GetSessionID() string {
	if s == nil {
		return ""
	}
	return s.SessionID
}

func (s *SSEPermissionEventData) GetToolName() ToolName {
	if s == nil {
		return ToolName{}
	}
	return s.ToolName
}

func (s *SSEPermissionEventData) GetType() string {
	if s == nil {
		return ""
	}
	return s.Type
}

// SSEPermissionEvent - Base SSE event with standard fields
type SSEPermissionEvent struct {
	// Event type identifier
	Event SSEPermissionEventEvent `json:"event"`
	// Unique sequential event identifier for ordering and reconnection
	ID string `json:"id"`
	// Client retry interval in milliseconds
	Retry *int64                 `json:"retry,omitempty"`
	Data  SSEPermissionEventData `json:"data"`
}

func (s SSEPermissionEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEPermissionEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"event", "id", "data"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEPermissionEvent) GetEvent() SSEPermissionEventEvent {
	if s == nil {
		return SSEPermissionEventEvent("")
	}
	return s.Event
}

func (s *SSEPermissionEvent) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSEPermissionEvent) GetRetry() *int64 {
	if s == nil {
		return nil
	}
	return s.Retry
}

func (s *SSEPermissionEvent) GetData() SSEPermissionEventData {
	if s == nil {
		return SSEPermissionEventData{}
	}
	return s.Data
}

// SSEToolExecutionCompleteEventEvent - Event type identifier
type SSEToolExecutionCompleteEventEvent string

const (
	SSEToolExecutionCompleteEventEventConnected                         SSEToolExecutionCompleteEventEvent = "connected"
	SSEToolExecutionCompleteEventEventHeartbeat                         SSEToolExecutionCompleteEventEvent = "heartbeat"
	SSEToolExecutionCompleteEventEventError                             SSEToolExecutionCompleteEventEvent = "error"
	SSEToolExecutionCompleteEventEventComplete                          SSEToolExecutionCompleteEventEvent = "complete"
	SSEToolExecutionCompleteEventEventThinking                          SSEToolExecutionCompleteEventEvent = "thinking"
	SSEToolExecutionCompleteEventEventContent                           SSEToolExecutionCompleteEventEvent = "content"
	SSEToolExecutionCompleteEventEventToolUseStart                      SSEToolExecutionCompleteEventEvent = "tool_use_start"
	SSEToolExecutionCompleteEventEventToolUseParameterStreamingComplete SSEToolExecutionCompleteEventEvent = "tool_use_parameter_streaming_complete"
	SSEToolExecutionCompleteEventEventToolUseParameterDelta             SSEToolExecutionCompleteEventEvent = "tool_use_parameter_delta"
	SSEToolExecutionCompleteEventEventToolExecutionStart                SSEToolExecutionCompleteEventEvent = "tool_execution_start"
	SSEToolExecutionCompleteEventEventToolExecutionComplete             SSEToolExecutionCompleteEventEvent = "tool_execution_complete"
	SSEToolExecutionCompleteEventEventPermission                        SSEToolExecutionCompleteEventEvent = "permission"
	SSEToolExecutionCompleteEventEventUserMessageCreated                SSEToolExecutionCompleteEventEvent = "user_message_created"
	SSEToolExecutionCompleteEventEventSessionCreated                    SSEToolExecutionCompleteEventEvent = "session_created"
	SSEToolExecutionCompleteEventEventSessionDeleted                    SSEToolExecutionCompleteEventEvent = "session_deleted"
)

func (e SSEToolExecutionCompleteEventEvent) ToPointer() *SSEToolExecutionCompleteEventEvent {
	return &e
}
func (e *SSEToolExecutionCompleteEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "connected":
		fallthrough
	case "heartbeat":
		fallthrough
	case "error":
		fallthrough
	case "complete":
		fallthrough
	case "thinking":
		fallthrough
	case "content":
		fallthrough
	case "tool_use_start":
		fallthrough
	case "tool_use_parameter_streaming_complete":
		fallthrough
	case "tool_use_parameter_delta":
		fallthrough
	case "tool_execution_start":
		fallthrough
	case "tool_execution_complete":
		fallthrough
	case "permission":
		fallthrough
	case "user_message_created":
		fallthrough
	case "session_created":
		fallthrough
	case "session_deleted":
		*e = SSEToolExecutionCompleteEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SSEToolExecutionCompleteEventEvent: %v", v)
	}
}

type SSEToolExecutionCompleteEventData struct {
	// ID of the parent tool call that spawned this subagent (for nested events)
	ParentToolCallID *string `json:"parentToolCallId,omitempty"`
	// Final execution progress description
	Progress string `json:"progress"`
	// Indicates if tool execution succeeded
	Success bool `json:"success"`
	// Tool call identifier
	ToolCallID string `json:"toolCallId"`
	// Tool name - either a core tool or MCP tool following {serverName}_{toolName} pattern
	ToolName ToolName `json:"toolName"`
	// Tool execution complete event type
	Type string `json:"type"`
}

func (s SSEToolExecutionCompleteEventData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEToolExecutionCompleteEventData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"progress", "success", "toolCallId", "toolName", "type"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEToolExecutionCompleteEventData) GetParentToolCallID() *string {
	if s == nil {
		return nil
	}
	return s.ParentToolCallID
}

func (s *SSEToolExecutionCompleteEventData) GetProgress() string {
	if s == nil {
		return ""
	}
	return s.Progress
}

func (s *SSEToolExecutionCompleteEventData) GetSuccess() bool {
	if s == nil {
		return false
	}
	return s.Success
}

func (s *SSEToolExecutionCompleteEventData) GetToolCallID() string {
	if s == nil {
		return ""
	}
	return s.ToolCallID
}

func (s *SSEToolExecutionCompleteEventData) GetToolName() ToolName {
	if s == nil {
		return ToolName{}
	}
	return s.ToolName
}

func (s *SSEToolExecutionCompleteEventData) GetType() string {
	if s == nil {
		return ""
	}
	return s.Type
}

// SSEToolExecutionCompleteEvent - Base SSE event with standard fields
type SSEToolExecutionCompleteEvent struct {
	// Event type identifier
	Event SSEToolExecutionCompleteEventEvent `json:"event"`
	// Unique sequential event identifier for ordering and reconnection
	ID string `json:"id"`
	// Client retry interval in milliseconds
	Retry *int64                            `json:"retry,omitempty"`
	Data  SSEToolExecutionCompleteEventData `json:"data"`
}

func (s SSEToolExecutionCompleteEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEToolExecutionCompleteEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"event", "id", "data"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEToolExecutionCompleteEvent) GetEvent() SSEToolExecutionCompleteEventEvent {
	if s == nil {
		return SSEToolExecutionCompleteEventEvent("")
	}
	return s.Event
}

func (s *SSEToolExecutionCompleteEvent) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSEToolExecutionCompleteEvent) GetRetry() *int64 {
	if s == nil {
		return nil
	}
	return s.Retry
}

func (s *SSEToolExecutionCompleteEvent) GetData() SSEToolExecutionCompleteEventData {
	if s == nil {
		return SSEToolExecutionCompleteEventData{}
	}
	return s.Data
}

// SSEToolExecutionStartEventEvent - Event type identifier
type SSEToolExecutionStartEventEvent string

const (
	SSEToolExecutionStartEventEventConnected                         SSEToolExecutionStartEventEvent = "connected"
	SSEToolExecutionStartEventEventHeartbeat                         SSEToolExecutionStartEventEvent = "heartbeat"
	SSEToolExecutionStartEventEventError                             SSEToolExecutionStartEventEvent = "error"
	SSEToolExecutionStartEventEventComplete                          SSEToolExecutionStartEventEvent = "complete"
	SSEToolExecutionStartEventEventThinking                          SSEToolExecutionStartEventEvent = "thinking"
	SSEToolExecutionStartEventEventContent                           SSEToolExecutionStartEventEvent = "content"
	SSEToolExecutionStartEventEventToolUseStart                      SSEToolExecutionStartEventEvent = "tool_use_start"
	SSEToolExecutionStartEventEventToolUseParameterStreamingComplete SSEToolExecutionStartEventEvent = "tool_use_parameter_streaming_complete"
	SSEToolExecutionStartEventEventToolUseParameterDelta             SSEToolExecutionStartEventEvent = "tool_use_parameter_delta"
	SSEToolExecutionStartEventEventToolExecutionStart                SSEToolExecutionStartEventEvent = "tool_execution_start"
	SSEToolExecutionStartEventEventToolExecutionComplete             SSEToolExecutionStartEventEvent = "tool_execution_complete"
	SSEToolExecutionStartEventEventPermission                        SSEToolExecutionStartEventEvent = "permission"
	SSEToolExecutionStartEventEventUserMessageCreated                SSEToolExecutionStartEventEvent = "user_message_created"
	SSEToolExecutionStartEventEventSessionCreated                    SSEToolExecutionStartEventEvent = "session_created"
	SSEToolExecutionStartEventEventSessionDeleted                    SSEToolExecutionStartEventEvent = "session_deleted"
)

func (e SSEToolExecutionStartEventEvent) ToPointer() *SSEToolExecutionStartEventEvent {
	return &e
}
func (e *SSEToolExecutionStartEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "connected":
		fallthrough
	case "heartbeat":
		fallthrough
	case "error":
		fallthrough
	case "complete":
		fallthrough
	case "thinking":
		fallthrough
	case "content":
		fallthrough
	case "tool_use_start":
		fallthrough
	case "tool_use_parameter_streaming_complete":
		fallthrough
	case "tool_use_parameter_delta":
		fallthrough
	case "tool_execution_start":
		fallthrough
	case "tool_execution_complete":
		fallthrough
	case "permission":
		fallthrough
	case "user_message_created":
		fallthrough
	case "session_created":
		fallthrough
	case "session_deleted":
		*e = SSEToolExecutionStartEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SSEToolExecutionStartEventEvent: %v", v)
	}
}

type SSEToolExecutionStartEventData struct {
	// ID of the parent tool call that spawned this subagent (for nested events)
	ParentToolCallID *string `json:"parentToolCallId,omitempty"`
	// Execution progress description
	Progress string `json:"progress"`
	// Tool call identifier
	ToolCallID string `json:"toolCallId"`
	// Tool name - either a core tool or MCP tool following {serverName}_{toolName} pattern
	ToolName ToolName `json:"toolName"`
	// Tool execution start event type
	Type string `json:"type"`
}

func (s SSEToolExecutionStartEventData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEToolExecutionStartEventData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"progress", "toolCallId", "toolName", "type"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEToolExecutionStartEventData) GetParentToolCallID() *string {
	if s == nil {
		return nil
	}
	return s.ParentToolCallID
}

func (s *SSEToolExecutionStartEventData) GetProgress() string {
	if s == nil {
		return ""
	}
	return s.Progress
}

func (s *SSEToolExecutionStartEventData) GetToolCallID() string {
	if s == nil {
		return ""
	}
	return s.ToolCallID
}

func (s *SSEToolExecutionStartEventData) GetToolName() ToolName {
	if s == nil {
		return ToolName{}
	}
	return s.ToolName
}

func (s *SSEToolExecutionStartEventData) GetType() string {
	if s == nil {
		return ""
	}
	return s.Type
}

// SSEToolExecutionStartEvent - Base SSE event with standard fields
type SSEToolExecutionStartEvent struct {
	// Event type identifier
	Event SSEToolExecutionStartEventEvent `json:"event"`
	// Unique sequential event identifier for ordering and reconnection
	ID string `json:"id"`
	// Client retry interval in milliseconds
	Retry *int64                         `json:"retry,omitempty"`
	Data  SSEToolExecutionStartEventData `json:"data"`
}

func (s SSEToolExecutionStartEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEToolExecutionStartEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"event", "id", "data"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEToolExecutionStartEvent) GetEvent() SSEToolExecutionStartEventEvent {
	if s == nil {
		return SSEToolExecutionStartEventEvent("")
	}
	return s.Event
}

func (s *SSEToolExecutionStartEvent) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSEToolExecutionStartEvent) GetRetry() *int64 {
	if s == nil {
		return nil
	}
	return s.Retry
}

func (s *SSEToolExecutionStartEvent) GetData() SSEToolExecutionStartEventData {
	if s == nil {
		return SSEToolExecutionStartEventData{}
	}
	return s.Data
}

// SSEToolUseParameterDeltaEventEvent - Event type identifier
type SSEToolUseParameterDeltaEventEvent string

const (
	SSEToolUseParameterDeltaEventEventConnected                         SSEToolUseParameterDeltaEventEvent = "connected"
	SSEToolUseParameterDeltaEventEventHeartbeat                         SSEToolUseParameterDeltaEventEvent = "heartbeat"
	SSEToolUseParameterDeltaEventEventError                             SSEToolUseParameterDeltaEventEvent = "error"
	SSEToolUseParameterDeltaEventEventComplete                          SSEToolUseParameterDeltaEventEvent = "complete"
	SSEToolUseParameterDeltaEventEventThinking                          SSEToolUseParameterDeltaEventEvent = "thinking"
	SSEToolUseParameterDeltaEventEventContent                           SSEToolUseParameterDeltaEventEvent = "content"
	SSEToolUseParameterDeltaEventEventToolUseStart                      SSEToolUseParameterDeltaEventEvent = "tool_use_start"
	SSEToolUseParameterDeltaEventEventToolUseParameterStreamingComplete SSEToolUseParameterDeltaEventEvent = "tool_use_parameter_streaming_complete"
	SSEToolUseParameterDeltaEventEventToolUseParameterDelta             SSEToolUseParameterDeltaEventEvent = "tool_use_parameter_delta"
	SSEToolUseParameterDeltaEventEventToolExecutionStart                SSEToolUseParameterDeltaEventEvent = "tool_execution_start"
	SSEToolUseParameterDeltaEventEventToolExecutionComplete             SSEToolUseParameterDeltaEventEvent = "tool_execution_complete"
	SSEToolUseParameterDeltaEventEventPermission                        SSEToolUseParameterDeltaEventEvent = "permission"
	SSEToolUseParameterDeltaEventEventUserMessageCreated                SSEToolUseParameterDeltaEventEvent = "user_message_created"
	SSEToolUseParameterDeltaEventEventSessionCreated                    SSEToolUseParameterDeltaEventEvent = "session_created"
	SSEToolUseParameterDeltaEventEventSessionDeleted                    SSEToolUseParameterDeltaEventEvent = "session_deleted"
)

func (e SSEToolUseParameterDeltaEventEvent) ToPointer() *SSEToolUseParameterDeltaEventEvent {
	return &e
}
func (e *SSEToolUseParameterDeltaEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "connected":
		fallthrough
	case "heartbeat":
		fallthrough
	case "error":
		fallthrough
	case "complete":
		fallthrough
	case "thinking":
		fallthrough
	case "content":
		fallthrough
	case "tool_use_start":
		fallthrough
	case "tool_use_parameter_streaming_complete":
		fallthrough
	case "tool_use_parameter_delta":
		fallthrough
	case "tool_execution_start":
		fallthrough
	case "tool_execution_complete":
		fallthrough
	case "permission":
		fallthrough
	case "user_message_created":
		fallthrough
	case "session_created":
		fallthrough
	case "session_deleted":
		*e = SSEToolUseParameterDeltaEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SSEToolUseParameterDeltaEventEvent: %v", v)
	}
}

type SSEToolUseParameterDeltaEventData struct {
	// ID of the assistant message this tool parameter delta belongs to
	AssistantMessageID *string `json:"assistantMessageId,omitempty"`
	// Partial JSON parameter delta - may not be parseable until complete
	Input string `json:"input"`
	// ID of the parent tool call that spawned this subagent (for nested events)
	ParentToolCallID *string `json:"parentToolCallId,omitempty"`
	// Tool call identifier for correlation
	ToolCallID string `json:"toolCallId"`
	// Tool use parameter delta event type
	Type string `json:"type"`
}

func (s SSEToolUseParameterDeltaEventData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEToolUseParameterDeltaEventData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"input", "toolCallId", "type"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEToolUseParameterDeltaEventData) GetAssistantMessageID() *string {
	if s == nil {
		return nil
	}
	return s.AssistantMessageID
}

func (s *SSEToolUseParameterDeltaEventData) GetInput() string {
	if s == nil {
		return ""
	}
	return s.Input
}

func (s *SSEToolUseParameterDeltaEventData) GetParentToolCallID() *string {
	if s == nil {
		return nil
	}
	return s.ParentToolCallID
}

func (s *SSEToolUseParameterDeltaEventData) GetToolCallID() string {
	if s == nil {
		return ""
	}
	return s.ToolCallID
}

func (s *SSEToolUseParameterDeltaEventData) GetType() string {
	if s == nil {
		return ""
	}
	return s.Type
}

// SSEToolUseParameterDeltaEvent - Base SSE event with standard fields
type SSEToolUseParameterDeltaEvent struct {
	// Event type identifier
	Event SSEToolUseParameterDeltaEventEvent `json:"event"`
	// Unique sequential event identifier for ordering and reconnection
	ID string `json:"id"`
	// Client retry interval in milliseconds
	Retry *int64                            `json:"retry,omitempty"`
	Data  SSEToolUseParameterDeltaEventData `json:"data"`
}

func (s SSEToolUseParameterDeltaEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEToolUseParameterDeltaEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"event", "id", "data"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEToolUseParameterDeltaEvent) GetEvent() SSEToolUseParameterDeltaEventEvent {
	if s == nil {
		return SSEToolUseParameterDeltaEventEvent("")
	}
	return s.Event
}

func (s *SSEToolUseParameterDeltaEvent) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSEToolUseParameterDeltaEvent) GetRetry() *int64 {
	if s == nil {
		return nil
	}
	return s.Retry
}

func (s *SSEToolUseParameterDeltaEvent) GetData() SSEToolUseParameterDeltaEventData {
	if s == nil {
		return SSEToolUseParameterDeltaEventData{}
	}
	return s.Data
}

// SSEToolUseParameterStreamingCompleteEventEvent - Event type identifier
type SSEToolUseParameterStreamingCompleteEventEvent string

const (
	SSEToolUseParameterStreamingCompleteEventEventConnected                         SSEToolUseParameterStreamingCompleteEventEvent = "connected"
	SSEToolUseParameterStreamingCompleteEventEventHeartbeat                         SSEToolUseParameterStreamingCompleteEventEvent = "heartbeat"
	SSEToolUseParameterStreamingCompleteEventEventError                             SSEToolUseParameterStreamingCompleteEventEvent = "error"
	SSEToolUseParameterStreamingCompleteEventEventComplete                          SSEToolUseParameterStreamingCompleteEventEvent = "complete"
	SSEToolUseParameterStreamingCompleteEventEventThinking                          SSEToolUseParameterStreamingCompleteEventEvent = "thinking"
	SSEToolUseParameterStreamingCompleteEventEventContent                           SSEToolUseParameterStreamingCompleteEventEvent = "content"
	SSEToolUseParameterStreamingCompleteEventEventToolUseStart                      SSEToolUseParameterStreamingCompleteEventEvent = "tool_use_start"
	SSEToolUseParameterStreamingCompleteEventEventToolUseParameterStreamingComplete SSEToolUseParameterStreamingCompleteEventEvent = "tool_use_parameter_streaming_complete"
	SSEToolUseParameterStreamingCompleteEventEventToolUseParameterDelta             SSEToolUseParameterStreamingCompleteEventEvent = "tool_use_parameter_delta"
	SSEToolUseParameterStreamingCompleteEventEventToolExecutionStart                SSEToolUseParameterStreamingCompleteEventEvent = "tool_execution_start"
	SSEToolUseParameterStreamingCompleteEventEventToolExecutionComplete             SSEToolUseParameterStreamingCompleteEventEvent = "tool_execution_complete"
	SSEToolUseParameterStreamingCompleteEventEventPermission                        SSEToolUseParameterStreamingCompleteEventEvent = "permission"
	SSEToolUseParameterStreamingCompleteEventEventUserMessageCreated                SSEToolUseParameterStreamingCompleteEventEvent = "user_message_created"
	SSEToolUseParameterStreamingCompleteEventEventSessionCreated                    SSEToolUseParameterStreamingCompleteEventEvent = "session_created"
	SSEToolUseParameterStreamingCompleteEventEventSessionDeleted                    SSEToolUseParameterStreamingCompleteEventEvent = "session_deleted"
)

func (e SSEToolUseParameterStreamingCompleteEventEvent) ToPointer() *SSEToolUseParameterStreamingCompleteEventEvent {
	return &e
}
func (e *SSEToolUseParameterStreamingCompleteEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "connected":
		fallthrough
	case "heartbeat":
		fallthrough
	case "error":
		fallthrough
	case "complete":
		fallthrough
	case "thinking":
		fallthrough
	case "content":
		fallthrough
	case "tool_use_start":
		fallthrough
	case "tool_use_parameter_streaming_complete":
		fallthrough
	case "tool_use_parameter_delta":
		fallthrough
	case "tool_execution_start":
		fallthrough
	case "tool_execution_complete":
		fallthrough
	case "permission":
		fallthrough
	case "user_message_created":
		fallthrough
	case "session_created":
		fallthrough
	case "session_deleted":
		*e = SSEToolUseParameterStreamingCompleteEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SSEToolUseParameterStreamingCompleteEventEvent: %v", v)
	}
}

type SSEToolUseParameterStreamingCompleteEventData struct {
	// ID of the assistant message this tool belongs to
	AssistantMessageID *string `json:"assistantMessageId,omitempty"`
	// Tool call identifier
	ID string `json:"id"`
	// Complete JSON-encoded tool input parameters
	Input string `json:"input"`
	// Tool name - either a core tool or MCP tool following {serverName}_{toolName} pattern
	Name ToolName `json:"name"`
	// ID of the parent tool call that spawned this subagent (for nested events)
	ParentToolCallID *string `json:"parentToolCallId,omitempty"`
	// Tool use parameter streaming complete event type
	Type string `json:"type"`
}

func (s SSEToolUseParameterStreamingCompleteEventData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEToolUseParameterStreamingCompleteEventData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"id", "input", "name", "type"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEToolUseParameterStreamingCompleteEventData) GetAssistantMessageID() *string {
	if s == nil {
		return nil
	}
	return s.AssistantMessageID
}

func (s *SSEToolUseParameterStreamingCompleteEventData) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSEToolUseParameterStreamingCompleteEventData) GetInput() string {
	if s == nil {
		return ""
	}
	return s.Input
}

func (s *SSEToolUseParameterStreamingCompleteEventData) GetName() ToolName {
	if s == nil {
		return ToolName{}
	}
	return s.Name
}

func (s *SSEToolUseParameterStreamingCompleteEventData) GetParentToolCallID() *string {
	if s == nil {
		return nil
	}
	return s.ParentToolCallID
}

func (s *SSEToolUseParameterStreamingCompleteEventData) GetType() string {
	if s == nil {
		return ""
	}
	return s.Type
}

// SSEToolUseParameterStreamingCompleteEvent - Base SSE event with standard fields
type SSEToolUseParameterStreamingCompleteEvent struct {
	// Event type identifier
	Event SSEToolUseParameterStreamingCompleteEventEvent `json:"event"`
	// Unique sequential event identifier for ordering and reconnection
	ID string `json:"id"`
	// Client retry interval in milliseconds
	Retry *int64                                        `json:"retry,omitempty"`
	Data  SSEToolUseParameterStreamingCompleteEventData `json:"data"`
}

func (s SSEToolUseParameterStreamingCompleteEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEToolUseParameterStreamingCompleteEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"event", "id", "data"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEToolUseParameterStreamingCompleteEvent) GetEvent() SSEToolUseParameterStreamingCompleteEventEvent {
	if s == nil {
		return SSEToolUseParameterStreamingCompleteEventEvent("")
	}
	return s.Event
}

func (s *SSEToolUseParameterStreamingCompleteEvent) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSEToolUseParameterStreamingCompleteEvent) GetRetry() *int64 {
	if s == nil {
		return nil
	}
	return s.Retry
}

func (s *SSEToolUseParameterStreamingCompleteEvent) GetData() SSEToolUseParameterStreamingCompleteEventData {
	if s == nil {
		return SSEToolUseParameterStreamingCompleteEventData{}
	}
	return s.Data
}

// SSEToolUseStartEventEvent - Event type identifier
type SSEToolUseStartEventEvent string

const (
	SSEToolUseStartEventEventConnected                         SSEToolUseStartEventEvent = "connected"
	SSEToolUseStartEventEventHeartbeat                         SSEToolUseStartEventEvent = "heartbeat"
	SSEToolUseStartEventEventError                             SSEToolUseStartEventEvent = "error"
	SSEToolUseStartEventEventComplete                          SSEToolUseStartEventEvent = "complete"
	SSEToolUseStartEventEventThinking                          SSEToolUseStartEventEvent = "thinking"
	SSEToolUseStartEventEventContent                           SSEToolUseStartEventEvent = "content"
	SSEToolUseStartEventEventToolUseStart                      SSEToolUseStartEventEvent = "tool_use_start"
	SSEToolUseStartEventEventToolUseParameterStreamingComplete SSEToolUseStartEventEvent = "tool_use_parameter_streaming_complete"
	SSEToolUseStartEventEventToolUseParameterDelta             SSEToolUseStartEventEvent = "tool_use_parameter_delta"
	SSEToolUseStartEventEventToolExecutionStart                SSEToolUseStartEventEvent = "tool_execution_start"
	SSEToolUseStartEventEventToolExecutionComplete             SSEToolUseStartEventEvent = "tool_execution_complete"
	SSEToolUseStartEventEventPermission                        SSEToolUseStartEventEvent = "permission"
	SSEToolUseStartEventEventUserMessageCreated                SSEToolUseStartEventEvent = "user_message_created"
	SSEToolUseStartEventEventSessionCreated                    SSEToolUseStartEventEvent = "session_created"
	SSEToolUseStartEventEventSessionDeleted                    SSEToolUseStartEventEvent = "session_deleted"
)

func (e SSEToolUseStartEventEvent) ToPointer() *SSEToolUseStartEventEvent {
	return &e
}
func (e *SSEToolUseStartEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "connected":
		fallthrough
	case "heartbeat":
		fallthrough
	case "error":
		fallthrough
	case "complete":
		fallthrough
	case "thinking":
		fallthrough
	case "content":
		fallthrough
	case "tool_use_start":
		fallthrough
	case "tool_use_parameter_streaming_complete":
		fallthrough
	case "tool_use_parameter_delta":
		fallthrough
	case "tool_execution_start":
		fallthrough
	case "tool_execution_complete":
		fallthrough
	case "permission":
		fallthrough
	case "user_message_created":
		fallthrough
	case "session_created":
		fallthrough
	case "session_deleted":
		*e = SSEToolUseStartEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SSEToolUseStartEventEvent: %v", v)
	}
}

type SSEToolUseStartEventData struct {
	// ID of the assistant message this tool belongs to
	AssistantMessageID *string `json:"assistantMessageId,omitempty"`
	// Tool call identifier
	ID string `json:"id"`
	// Tool name - either a core tool or MCP tool following {serverName}_{toolName} pattern
	Name ToolName `json:"name"`
	// ID of the parent tool call that spawned this subagent (for nested events)
	ParentToolCallID *string `json:"parentToolCallId,omitempty"`
	// Tool use start event type
	Type string `json:"type"`
}

func (s SSEToolUseStartEventData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEToolUseStartEventData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"id", "name", "type"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEToolUseStartEventData) GetAssistantMessageID() *string {
	if s == nil {
		return nil
	}
	return s.AssistantMessageID
}

func (s *SSEToolUseStartEventData) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSEToolUseStartEventData) GetName() ToolName {
	if s == nil {
		return ToolName{}
	}
	return s.Name
}

func (s *SSEToolUseStartEventData) GetParentToolCallID() *string {
	if s == nil {
		return nil
	}
	return s.ParentToolCallID
}

func (s *SSEToolUseStartEventData) GetType() string {
	if s == nil {
		return ""
	}
	return s.Type
}

// SSEToolUseStartEvent - Base SSE event with standard fields
type SSEToolUseStartEvent struct {
	// Event type identifier
	Event SSEToolUseStartEventEvent `json:"event"`
	// Unique sequential event identifier for ordering and reconnection
	ID string `json:"id"`
	// Client retry interval in milliseconds
	Retry *int64                   `json:"retry,omitempty"`
	Data  SSEToolUseStartEventData `json:"data"`
}

func (s SSEToolUseStartEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEToolUseStartEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"event", "id", "data"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEToolUseStartEvent) GetEvent() SSEToolUseStartEventEvent {
	if s == nil {
		return SSEToolUseStartEventEvent("")
	}
	return s.Event
}

func (s *SSEToolUseStartEvent) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSEToolUseStartEvent) GetRetry() *int64 {
	if s == nil {
		return nil
	}
	return s.Retry
}

func (s *SSEToolUseStartEvent) GetData() SSEToolUseStartEventData {
	if s == nil {
		return SSEToolUseStartEventData{}
	}
	return s.Data
}

// SSEContentEventEvent - Event type identifier
type SSEContentEventEvent string

const (
	SSEContentEventEventConnected                         SSEContentEventEvent = "connected"
	SSEContentEventEventHeartbeat                         SSEContentEventEvent = "heartbeat"
	SSEContentEventEventError                             SSEContentEventEvent = "error"
	SSEContentEventEventComplete                          SSEContentEventEvent = "complete"
	SSEContentEventEventThinking                          SSEContentEventEvent = "thinking"
	SSEContentEventEventContent                           SSEContentEventEvent = "content"
	SSEContentEventEventToolUseStart                      SSEContentEventEvent = "tool_use_start"
	SSEContentEventEventToolUseParameterStreamingComplete SSEContentEventEvent = "tool_use_parameter_streaming_complete"
	SSEContentEventEventToolUseParameterDelta             SSEContentEventEvent = "tool_use_parameter_delta"
	SSEContentEventEventToolExecutionStart                SSEContentEventEvent = "tool_execution_start"
	SSEContentEventEventToolExecutionComplete             SSEContentEventEvent = "tool_execution_complete"
	SSEContentEventEventPermission                        SSEContentEventEvent = "permission"
	SSEContentEventEventUserMessageCreated                SSEContentEventEvent = "user_message_created"
	SSEContentEventEventSessionCreated                    SSEContentEventEvent = "session_created"
	SSEContentEventEventSessionDeleted                    SSEContentEventEvent = "session_deleted"
)

func (e SSEContentEventEvent) ToPointer() *SSEContentEventEvent {
	return &e
}
func (e *SSEContentEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "connected":
		fallthrough
	case "heartbeat":
		fallthrough
	case "error":
		fallthrough
	case "complete":
		fallthrough
	case "thinking":
		fallthrough
	case "content":
		fallthrough
	case "tool_use_start":
		fallthrough
	case "tool_use_parameter_streaming_complete":
		fallthrough
	case "tool_use_parameter_delta":
		fallthrough
	case "tool_execution_start":
		fallthrough
	case "tool_execution_complete":
		fallthrough
	case "permission":
		fallthrough
	case "user_message_created":
		fallthrough
	case "session_created":
		fallthrough
	case "session_deleted":
		*e = SSEContentEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SSEContentEventEvent: %v", v)
	}
}

type SSEContentEventData struct {
	// ID of the assistant message this content belongs to
	AssistantMessageID *string `json:"assistantMessageId,omitempty"`
	// Streaming content delta
	Content string `json:"content"`
	// ID of the parent tool call that spawned this subagent (for nested events)
	ParentToolCallID *string `json:"parentToolCallId,omitempty"`
	// Content event type
	Type string `json:"type"`
}

func (s SSEContentEventData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEContentEventData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"content", "type"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEContentEventData) GetAssistantMessageID() *string {
	if s == nil {
		return nil
	}
	return s.AssistantMessageID
}

func (s *SSEContentEventData) GetContent() string {
	if s == nil {
		return ""
	}
	return s.Content
}

func (s *SSEContentEventData) GetParentToolCallID() *string {
	if s == nil {
		return nil
	}
	return s.ParentToolCallID
}

func (s *SSEContentEventData) GetType() string {
	if s == nil {
		return ""
	}
	return s.Type
}

// SSEContentEvent - Base SSE event with standard fields
type SSEContentEvent struct {
	// Event type identifier
	Event SSEContentEventEvent `json:"event"`
	// Unique sequential event identifier for ordering and reconnection
	ID string `json:"id"`
	// Client retry interval in milliseconds
	Retry *int64              `json:"retry,omitempty"`
	Data  SSEContentEventData `json:"data"`
}

func (s SSEContentEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEContentEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"event", "id", "data"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEContentEvent) GetEvent() SSEContentEventEvent {
	if s == nil {
		return SSEContentEventEvent("")
	}
	return s.Event
}

func (s *SSEContentEvent) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSEContentEvent) GetRetry() *int64 {
	if s == nil {
		return nil
	}
	return s.Retry
}

func (s *SSEContentEvent) GetData() SSEContentEventData {
	if s == nil {
		return SSEContentEventData{}
	}
	return s.Data
}

// SSEThinkingEventEvent - Event type identifier
type SSEThinkingEventEvent string

const (
	SSEThinkingEventEventConnected                         SSEThinkingEventEvent = "connected"
	SSEThinkingEventEventHeartbeat                         SSEThinkingEventEvent = "heartbeat"
	SSEThinkingEventEventError                             SSEThinkingEventEvent = "error"
	SSEThinkingEventEventComplete                          SSEThinkingEventEvent = "complete"
	SSEThinkingEventEventThinking                          SSEThinkingEventEvent = "thinking"
	SSEThinkingEventEventContent                           SSEThinkingEventEvent = "content"
	SSEThinkingEventEventToolUseStart                      SSEThinkingEventEvent = "tool_use_start"
	SSEThinkingEventEventToolUseParameterStreamingComplete SSEThinkingEventEvent = "tool_use_parameter_streaming_complete"
	SSEThinkingEventEventToolUseParameterDelta             SSEThinkingEventEvent = "tool_use_parameter_delta"
	SSEThinkingEventEventToolExecutionStart                SSEThinkingEventEvent = "tool_execution_start"
	SSEThinkingEventEventToolExecutionComplete             SSEThinkingEventEvent = "tool_execution_complete"
	SSEThinkingEventEventPermission                        SSEThinkingEventEvent = "permission"
	SSEThinkingEventEventUserMessageCreated                SSEThinkingEventEvent = "user_message_created"
	SSEThinkingEventEventSessionCreated                    SSEThinkingEventEvent = "session_created"
	SSEThinkingEventEventSessionDeleted                    SSEThinkingEventEvent = "session_deleted"
)

func (e SSEThinkingEventEvent) ToPointer() *SSEThinkingEventEvent {
	return &e
}
func (e *SSEThinkingEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "connected":
		fallthrough
	case "heartbeat":
		fallthrough
	case "error":
		fallthrough
	case "complete":
		fallthrough
	case "thinking":
		fallthrough
	case "content":
		fallthrough
	case "tool_use_start":
		fallthrough
	case "tool_use_parameter_streaming_complete":
		fallthrough
	case "tool_use_parameter_delta":
		fallthrough
	case "tool_execution_start":
		fallthrough
	case "tool_execution_complete":
		fallthrough
	case "permission":
		fallthrough
	case "user_message_created":
		fallthrough
	case "session_created":
		fallthrough
	case "session_deleted":
		*e = SSEThinkingEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SSEThinkingEventEvent: %v", v)
	}
}

type SSEThinkingEventData struct {
	// ID of the assistant message this thinking belongs to
	AssistantMessageID *string `json:"assistantMessageId,omitempty"`
	// Thinking or reasoning content
	Content string `json:"content"`
	// ID of the parent tool call that spawned this subagent (for nested events)
	ParentToolCallID *string `json:"parentToolCallId,omitempty"`
	// Thinking event type
	Type string `json:"type"`
}

func (s SSEThinkingEventData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEThinkingEventData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"content", "type"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEThinkingEventData) GetAssistantMessageID() *string {
	if s == nil {
		return nil
	}
	return s.AssistantMessageID
}

func (s *SSEThinkingEventData) GetContent() string {
	if s == nil {
		return ""
	}
	return s.Content
}

func (s *SSEThinkingEventData) GetParentToolCallID() *string {
	if s == nil {
		return nil
	}
	return s.ParentToolCallID
}

func (s *SSEThinkingEventData) GetType() string {
	if s == nil {
		return ""
	}
	return s.Type
}

// SSEThinkingEvent - Base SSE event with standard fields
type SSEThinkingEvent struct {
	// Event type identifier
	Event SSEThinkingEventEvent `json:"event"`
	// Unique sequential event identifier for ordering and reconnection
	ID string `json:"id"`
	// Client retry interval in milliseconds
	Retry *int64               `json:"retry,omitempty"`
	Data  SSEThinkingEventData `json:"data"`
}

func (s SSEThinkingEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEThinkingEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"event", "id", "data"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEThinkingEvent) GetEvent() SSEThinkingEventEvent {
	if s == nil {
		return SSEThinkingEventEvent("")
	}
	return s.Event
}

func (s *SSEThinkingEvent) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSEThinkingEvent) GetRetry() *int64 {
	if s == nil {
		return nil
	}
	return s.Retry
}

func (s *SSEThinkingEvent) GetData() SSEThinkingEventData {
	if s == nil {
		return SSEThinkingEventData{}
	}
	return s.Data
}

// SSECompleteEventEvent - Event type identifier
type SSECompleteEventEvent string

const (
	SSECompleteEventEventConnected                         SSECompleteEventEvent = "connected"
	SSECompleteEventEventHeartbeat                         SSECompleteEventEvent = "heartbeat"
	SSECompleteEventEventError                             SSECompleteEventEvent = "error"
	SSECompleteEventEventComplete                          SSECompleteEventEvent = "complete"
	SSECompleteEventEventThinking                          SSECompleteEventEvent = "thinking"
	SSECompleteEventEventContent                           SSECompleteEventEvent = "content"
	SSECompleteEventEventToolUseStart                      SSECompleteEventEvent = "tool_use_start"
	SSECompleteEventEventToolUseParameterStreamingComplete SSECompleteEventEvent = "tool_use_parameter_streaming_complete"
	SSECompleteEventEventToolUseParameterDelta             SSECompleteEventEvent = "tool_use_parameter_delta"
	SSECompleteEventEventToolExecutionStart                SSECompleteEventEvent = "tool_execution_start"
	SSECompleteEventEventToolExecutionComplete             SSECompleteEventEvent = "tool_execution_complete"
	SSECompleteEventEventPermission                        SSECompleteEventEvent = "permission"
	SSECompleteEventEventUserMessageCreated                SSECompleteEventEvent = "user_message_created"
	SSECompleteEventEventSessionCreated                    SSECompleteEventEvent = "session_created"
	SSECompleteEventEventSessionDeleted                    SSECompleteEventEvent = "session_deleted"
)

func (e SSECompleteEventEvent) ToPointer() *SSECompleteEventEvent {
	return &e
}
func (e *SSECompleteEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "connected":
		fallthrough
	case "heartbeat":
		fallthrough
	case "error":
		fallthrough
	case "complete":
		fallthrough
	case "thinking":
		fallthrough
	case "content":
		fallthrough
	case "tool_use_start":
		fallthrough
	case "tool_use_parameter_streaming_complete":
		fallthrough
	case "tool_use_parameter_delta":
		fallthrough
	case "tool_execution_start":
		fallthrough
	case "tool_execution_complete":
		fallthrough
	case "permission":
		fallthrough
	case "user_message_created":
		fallthrough
	case "session_created":
		fallthrough
	case "session_deleted":
		*e = SSECompleteEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SSECompleteEventEvent: %v", v)
	}
}

type SSECompleteEventData struct {
	// Final response content
	Content *string `json:"content,omitempty"`
	// Indicates message processing completion
	Done bool `json:"done"`
	// Completed message identifier
	MessageID *string `json:"messageId,omitempty"`
	// ID of the parent tool call that spawned this subagent (for nested events)
	ParentToolCallID *string `json:"parentToolCallId,omitempty"`
	// Optional reasoning content
	Reasoning *string `json:"reasoning,omitempty"`
	// Duration of reasoning process in milliseconds
	ReasoningDuration *int64 `json:"reasoningDuration,omitempty"`
	// Completion type
	Type string `json:"type"`
}

func (s SSECompleteEventData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSECompleteEventData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"done", "type"}); err != nil {
		return err
	}
	return nil
}

func (s *SSECompleteEventData) GetContent() *string {
	if s == nil {
		return nil
	}
	return s.Content
}

func (s *SSECompleteEventData) GetDone() bool {
	if s == nil {
		return false
	}
	return s.Done
}

func (s *SSECompleteEventData) GetMessageID() *string {
	if s == nil {
		return nil
	}
	return s.MessageID
}

func (s *SSECompleteEventData) GetParentToolCallID() *string {
	if s == nil {
		return nil
	}
	return s.ParentToolCallID
}

func (s *SSECompleteEventData) GetReasoning() *string {
	if s == nil {
		return nil
	}
	return s.Reasoning
}

func (s *SSECompleteEventData) GetReasoningDuration() *int64 {
	if s == nil {
		return nil
	}
	return s.ReasoningDuration
}

func (s *SSECompleteEventData) GetType() string {
	if s == nil {
		return ""
	}
	return s.Type
}

// SSECompleteEvent - Base SSE event with standard fields
type SSECompleteEvent struct {
	// Event type identifier
	Event SSECompleteEventEvent `json:"event"`
	// Unique sequential event identifier for ordering and reconnection
	ID string `json:"id"`
	// Client retry interval in milliseconds
	Retry *int64               `json:"retry,omitempty"`
	Data  SSECompleteEventData `json:"data"`
}

func (s SSECompleteEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSECompleteEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"event", "id", "data"}); err != nil {
		return err
	}
	return nil
}

func (s *SSECompleteEvent) GetEvent() SSECompleteEventEvent {
	if s == nil {
		return SSECompleteEventEvent("")
	}
	return s.Event
}

func (s *SSECompleteEvent) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSECompleteEvent) GetRetry() *int64 {
	if s == nil {
		return nil
	}
	return s.Retry
}

func (s *SSECompleteEvent) GetData() SSECompleteEventData {
	if s == nil {
		return SSECompleteEventData{}
	}
	return s.Data
}

// SSEErrorEventEvent - Event type identifier
type SSEErrorEventEvent string

const (
	SSEErrorEventEventConnected                         SSEErrorEventEvent = "connected"
	SSEErrorEventEventHeartbeat                         SSEErrorEventEvent = "heartbeat"
	SSEErrorEventEventError                             SSEErrorEventEvent = "error"
	SSEErrorEventEventComplete                          SSEErrorEventEvent = "complete"
	SSEErrorEventEventThinking                          SSEErrorEventEvent = "thinking"
	SSEErrorEventEventContent                           SSEErrorEventEvent = "content"
	SSEErrorEventEventToolUseStart                      SSEErrorEventEvent = "tool_use_start"
	SSEErrorEventEventToolUseParameterStreamingComplete SSEErrorEventEvent = "tool_use_parameter_streaming_complete"
	SSEErrorEventEventToolUseParameterDelta             SSEErrorEventEvent = "tool_use_parameter_delta"
	SSEErrorEventEventToolExecutionStart                SSEErrorEventEvent = "tool_execution_start"
	SSEErrorEventEventToolExecutionComplete             SSEErrorEventEvent = "tool_execution_complete"
	SSEErrorEventEventPermission                        SSEErrorEventEvent = "permission"
	SSEErrorEventEventUserMessageCreated                SSEErrorEventEvent = "user_message_created"
	SSEErrorEventEventSessionCreated                    SSEErrorEventEvent = "session_created"
	SSEErrorEventEventSessionDeleted                    SSEErrorEventEvent = "session_deleted"
)

func (e SSEErrorEventEvent) ToPointer() *SSEErrorEventEvent {
	return &e
}
func (e *SSEErrorEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "connected":
		fallthrough
	case "heartbeat":
		fallthrough
	case "error":
		fallthrough
	case "complete":
		fallthrough
	case "thinking":
		fallthrough
	case "content":
		fallthrough
	case "tool_use_start":
		fallthrough
	case "tool_use_parameter_streaming_complete":
		fallthrough
	case "tool_use_parameter_delta":
		fallthrough
	case "tool_execution_start":
		fallthrough
	case "tool_execution_complete":
		fallthrough
	case "permission":
		fallthrough
	case "user_message_created":
		fallthrough
	case "session_created":
		fallthrough
	case "session_deleted":
		*e = SSEErrorEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SSEErrorEventEvent: %v", v)
	}
}

type SSEErrorEventData struct {
	// Current retry attempt number
	Attempt *int64 `json:"attempt,omitempty"`
	// Error message description
	Error string `json:"error"`
	// Maximum number of retry attempts
	MaxAttempts *int64 `json:"maxAttempts,omitempty"`
	// ID of the parent tool call that spawned this subagent (for nested events)
	ParentToolCallID *string `json:"parentToolCallId,omitempty"`
	// Milliseconds to wait before retry
	RetryAfter *int64 `json:"retryAfter,omitempty"`
	// Error type classification
	Type *string `json:"type,omitempty"`
}

func (s SSEErrorEventData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEErrorEventData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"error"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEErrorEventData) GetAttempt() *int64 {
	if s == nil {
		return nil
	}
	return s.Attempt
}

func (s *SSEErrorEventData) GetError() string {
	if s == nil {
		return ""
	}
	return s.Error
}

func (s *SSEErrorEventData) GetMaxAttempts() *int64 {
	if s == nil {
		return nil
	}
	return s.MaxAttempts
}

func (s *SSEErrorEventData) GetParentToolCallID() *string {
	if s == nil {
		return nil
	}
	return s.ParentToolCallID
}

func (s *SSEErrorEventData) GetRetryAfter() *int64 {
	if s == nil {
		return nil
	}
	return s.RetryAfter
}

func (s *SSEErrorEventData) GetType() *string {
	if s == nil {
		return nil
	}
	return s.Type
}

// SSEErrorEvent - Base SSE event with standard fields
type SSEErrorEvent struct {
	// Event type identifier
	Event SSEErrorEventEvent `json:"event"`
	// Unique sequential event identifier for ordering and reconnection
	ID string `json:"id"`
	// Client retry interval in milliseconds
	Retry *int64            `json:"retry,omitempty"`
	Data  SSEErrorEventData `json:"data"`
}

func (s SSEErrorEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEErrorEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"event", "id", "data"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEErrorEvent) GetEvent() SSEErrorEventEvent {
	if s == nil {
		return SSEErrorEventEvent("")
	}
	return s.Event
}

func (s *SSEErrorEvent) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSEErrorEvent) GetRetry() *int64 {
	if s == nil {
		return nil
	}
	return s.Retry
}

func (s *SSEErrorEvent) GetData() SSEErrorEventData {
	if s == nil {
		return SSEErrorEventData{}
	}
	return s.Data
}

// SSEHeartbeatEventEvent - Event type identifier
type SSEHeartbeatEventEvent string

const (
	SSEHeartbeatEventEventConnected                         SSEHeartbeatEventEvent = "connected"
	SSEHeartbeatEventEventHeartbeat                         SSEHeartbeatEventEvent = "heartbeat"
	SSEHeartbeatEventEventError                             SSEHeartbeatEventEvent = "error"
	SSEHeartbeatEventEventComplete                          SSEHeartbeatEventEvent = "complete"
	SSEHeartbeatEventEventThinking                          SSEHeartbeatEventEvent = "thinking"
	SSEHeartbeatEventEventContent                           SSEHeartbeatEventEvent = "content"
	SSEHeartbeatEventEventToolUseStart                      SSEHeartbeatEventEvent = "tool_use_start"
	SSEHeartbeatEventEventToolUseParameterStreamingComplete SSEHeartbeatEventEvent = "tool_use_parameter_streaming_complete"
	SSEHeartbeatEventEventToolUseParameterDelta             SSEHeartbeatEventEvent = "tool_use_parameter_delta"
	SSEHeartbeatEventEventToolExecutionStart                SSEHeartbeatEventEvent = "tool_execution_start"
	SSEHeartbeatEventEventToolExecutionComplete             SSEHeartbeatEventEvent = "tool_execution_complete"
	SSEHeartbeatEventEventPermission                        SSEHeartbeatEventEvent = "permission"
	SSEHeartbeatEventEventUserMessageCreated                SSEHeartbeatEventEvent = "user_message_created"
	SSEHeartbeatEventEventSessionCreated                    SSEHeartbeatEventEvent = "session_created"
	SSEHeartbeatEventEventSessionDeleted                    SSEHeartbeatEventEvent = "session_deleted"
)

func (e SSEHeartbeatEventEvent) ToPointer() *SSEHeartbeatEventEvent {
	return &e
}
func (e *SSEHeartbeatEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "connected":
		fallthrough
	case "heartbeat":
		fallthrough
	case "error":
		fallthrough
	case "complete":
		fallthrough
	case "thinking":
		fallthrough
	case "content":
		fallthrough
	case "tool_use_start":
		fallthrough
	case "tool_use_parameter_streaming_complete":
		fallthrough
	case "tool_use_parameter_delta":
		fallthrough
	case "tool_execution_start":
		fallthrough
	case "tool_execution_complete":
		fallthrough
	case "permission":
		fallthrough
	case "user_message_created":
		fallthrough
	case "session_created":
		fallthrough
	case "session_deleted":
		*e = SSEHeartbeatEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SSEHeartbeatEventEvent: %v", v)
	}
}

type SSEHeartbeatEventData struct {
	// Heartbeat type
	Type string `json:"type"`
}

func (s SSEHeartbeatEventData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEHeartbeatEventData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEHeartbeatEventData) GetType() string {
	if s == nil {
		return ""
	}
	return s.Type
}

// SSEHeartbeatEvent - Base SSE event with standard fields
type SSEHeartbeatEvent struct {
	// Event type identifier
	Event SSEHeartbeatEventEvent `json:"event"`
	// Unique sequential event identifier for ordering and reconnection
	ID string `json:"id"`
	// Client retry interval in milliseconds
	Retry *int64                `json:"retry,omitempty"`
	Data  SSEHeartbeatEventData `json:"data"`
}

func (s SSEHeartbeatEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEHeartbeatEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"event", "id", "data"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEHeartbeatEvent) GetEvent() SSEHeartbeatEventEvent {
	if s == nil {
		return SSEHeartbeatEventEvent("")
	}
	return s.Event
}

func (s *SSEHeartbeatEvent) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSEHeartbeatEvent) GetRetry() *int64 {
	if s == nil {
		return nil
	}
	return s.Retry
}

func (s *SSEHeartbeatEvent) GetData() SSEHeartbeatEventData {
	if s == nil {
		return SSEHeartbeatEventData{}
	}
	return s.Data
}

// SSEConnectedEventEvent - Event type identifier
type SSEConnectedEventEvent string

const (
	SSEConnectedEventEventConnected                         SSEConnectedEventEvent = "connected"
	SSEConnectedEventEventHeartbeat                         SSEConnectedEventEvent = "heartbeat"
	SSEConnectedEventEventError                             SSEConnectedEventEvent = "error"
	SSEConnectedEventEventComplete                          SSEConnectedEventEvent = "complete"
	SSEConnectedEventEventThinking                          SSEConnectedEventEvent = "thinking"
	SSEConnectedEventEventContent                           SSEConnectedEventEvent = "content"
	SSEConnectedEventEventToolUseStart                      SSEConnectedEventEvent = "tool_use_start"
	SSEConnectedEventEventToolUseParameterStreamingComplete SSEConnectedEventEvent = "tool_use_parameter_streaming_complete"
	SSEConnectedEventEventToolUseParameterDelta             SSEConnectedEventEvent = "tool_use_parameter_delta"
	SSEConnectedEventEventToolExecutionStart                SSEConnectedEventEvent = "tool_execution_start"
	SSEConnectedEventEventToolExecutionComplete             SSEConnectedEventEvent = "tool_execution_complete"
	SSEConnectedEventEventPermission                        SSEConnectedEventEvent = "permission"
	SSEConnectedEventEventUserMessageCreated                SSEConnectedEventEvent = "user_message_created"
	SSEConnectedEventEventSessionCreated                    SSEConnectedEventEvent = "session_created"
	SSEConnectedEventEventSessionDeleted                    SSEConnectedEventEvent = "session_deleted"
)

func (e SSEConnectedEventEvent) ToPointer() *SSEConnectedEventEvent {
	return &e
}
func (e *SSEConnectedEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "connected":
		fallthrough
	case "heartbeat":
		fallthrough
	case "error":
		fallthrough
	case "complete":
		fallthrough
	case "thinking":
		fallthrough
	case "content":
		fallthrough
	case "tool_use_start":
		fallthrough
	case "tool_use_parameter_streaming_complete":
		fallthrough
	case "tool_use_parameter_delta":
		fallthrough
	case "tool_execution_start":
		fallthrough
	case "tool_execution_complete":
		fallthrough
	case "permission":
		fallthrough
	case "user_message_created":
		fallthrough
	case "session_created":
		fallthrough
	case "session_deleted":
		*e = SSEConnectedEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SSEConnectedEventEvent: %v", v)
	}
}

type SSEConnectedEventData struct {
	// Session identifier for the connected stream
	SessionID string `json:"sessionId"`
}

func (s SSEConnectedEventData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEConnectedEventData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"sessionId"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEConnectedEventData) GetSessionID() string {
	if s == nil {
		return ""
	}
	return s.SessionID
}

// SSEConnectedEvent - Base SSE event with standard fields
type SSEConnectedEvent struct {
	// Event type identifier
	Event SSEConnectedEventEvent `json:"event"`
	// Unique sequential event identifier for ordering and reconnection
	ID string `json:"id"`
	// Client retry interval in milliseconds
	Retry *int64                `json:"retry,omitempty"`
	Data  SSEConnectedEventData `json:"data"`
}

func (s SSEConnectedEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSEConnectedEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"event", "id", "data"}); err != nil {
		return err
	}
	return nil
}

func (s *SSEConnectedEvent) GetEvent() SSEConnectedEventEvent {
	if s == nil {
		return SSEConnectedEventEvent("")
	}
	return s.Event
}

func (s *SSEConnectedEvent) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSEConnectedEvent) GetRetry() *int64 {
	if s == nil {
		return nil
	}
	return s.Retry
}

func (s *SSEConnectedEvent) GetData() SSEConnectedEventData {
	if s == nil {
		return SSEConnectedEventData{}
	}
	return s.Data
}

type SSEEventStreamType string

const (
	SSEEventStreamTypeComplete                          SSEEventStreamType = "complete"
	SSEEventStreamTypeConnected                         SSEEventStreamType = "connected"
	SSEEventStreamTypeContent                           SSEEventStreamType = "content"
	SSEEventStreamTypeError                             SSEEventStreamType = "error"
	SSEEventStreamTypeHeartbeat                         SSEEventStreamType = "heartbeat"
	SSEEventStreamTypePermission                        SSEEventStreamType = "permission"
	SSEEventStreamTypeSessionCreated                    SSEEventStreamType = "session_created"
	SSEEventStreamTypeSessionDeleted                    SSEEventStreamType = "session_deleted"
	SSEEventStreamTypeThinking                          SSEEventStreamType = "thinking"
	SSEEventStreamTypeToolExecutionComplete             SSEEventStreamType = "tool_execution_complete"
	SSEEventStreamTypeToolExecutionStart                SSEEventStreamType = "tool_execution_start"
	SSEEventStreamTypeToolUseParameterDelta             SSEEventStreamType = "tool_use_parameter_delta"
	SSEEventStreamTypeToolUseParameterStreamingComplete SSEEventStreamType = "tool_use_parameter_streaming_complete"
	SSEEventStreamTypeToolUseStart                      SSEEventStreamType = "tool_use_start"
	SSEEventStreamTypeUserMessageCreated                SSEEventStreamType = "user_message_created"
)

// SSEEventStream - Server-Sent Event stream with discriminated event types
type SSEEventStream struct {
	SSEConnectedEvent                         *SSEConnectedEvent                         `queryParam:"inline,name=SSEEventStream"`
	SSEHeartbeatEvent                         *SSEHeartbeatEvent                         `queryParam:"inline,name=SSEEventStream"`
	SSEErrorEvent                             *SSEErrorEvent                             `queryParam:"inline,name=SSEEventStream"`
	SSECompleteEvent                          *SSECompleteEvent                          `queryParam:"inline,name=SSEEventStream"`
	SSEThinkingEvent                          *SSEThinkingEvent                          `queryParam:"inline,name=SSEEventStream"`
	SSEContentEvent                           *SSEContentEvent                           `queryParam:"inline,name=SSEEventStream"`
	SSEToolUseStartEvent                      *SSEToolUseStartEvent                      `queryParam:"inline,name=SSEEventStream"`
	SSEToolUseParameterStreamingCompleteEvent *SSEToolUseParameterStreamingCompleteEvent `queryParam:"inline,name=SSEEventStream"`
	SSEToolUseParameterDeltaEvent             *SSEToolUseParameterDeltaEvent             `queryParam:"inline,name=SSEEventStream"`
	SSEToolExecutionStartEvent                *SSEToolExecutionStartEvent                `queryParam:"inline,name=SSEEventStream"`
	SSEToolExecutionCompleteEvent             *SSEToolExecutionCompleteEvent             `queryParam:"inline,name=SSEEventStream"`
	SSEPermissionEvent                        *SSEPermissionEvent                        `queryParam:"inline,name=SSEEventStream"`
	SSEUserMessageCreatedEvent                *SSEUserMessageCreatedEvent                `queryParam:"inline,name=SSEEventStream"`
	SSESessionCreatedEvent                    *SSESessionCreatedEvent                    `queryParam:"inline,name=SSEEventStream"`
	SSESessionDeletedEvent                    *SSESessionDeletedEvent                    `queryParam:"inline,name=SSEEventStream"`

	Type SSEEventStreamType
}

func CreateSSEEventStreamComplete(complete SSECompleteEvent) SSEEventStream {
	typ := SSEEventStreamTypeComplete

	typStr := SSECompleteEventEvent(typ)
	complete.Event = typStr

	return SSEEventStream{
		SSECompleteEvent: &complete,
		Type:             typ,
	}
}

func CreateSSEEventStreamConnected(connected SSEConnectedEvent) SSEEventStream {
	typ := SSEEventStreamTypeConnected

	typStr := SSEConnectedEventEvent(typ)
	connected.Event = typStr

	return SSEEventStream{
		SSEConnectedEvent: &connected,
		Type:              typ,
	}
}

func CreateSSEEventStreamContent(content SSEContentEvent) SSEEventStream {
	typ := SSEEventStreamTypeContent

	typStr := SSEContentEventEvent(typ)
	content.Event = typStr

	return SSEEventStream{
		SSEContentEvent: &content,
		Type:            typ,
	}
}

func CreateSSEEventStreamError(errorT SSEErrorEvent) SSEEventStream {
	typ := SSEEventStreamTypeError

	typStr := SSEErrorEventEvent(typ)
	errorT.Event = typStr

	return SSEEventStream{
		SSEErrorEvent: &errorT,
		Type:          typ,
	}
}

func CreateSSEEventStreamHeartbeat(heartbeat SSEHeartbeatEvent) SSEEventStream {
	typ := SSEEventStreamTypeHeartbeat

	typStr := SSEHeartbeatEventEvent(typ)
	heartbeat.Event = typStr

	return SSEEventStream{
		SSEHeartbeatEvent: &heartbeat,
		Type:              typ,
	}
}

func CreateSSEEventStreamPermission(permission SSEPermissionEvent) SSEEventStream {
	typ := SSEEventStreamTypePermission

	typStr := SSEPermissionEventEvent(typ)
	permission.Event = typStr

	return SSEEventStream{
		SSEPermissionEvent: &permission,
		Type:               typ,
	}
}

func CreateSSEEventStreamSessionCreated(sessionCreated SSESessionCreatedEvent) SSEEventStream {
	typ := SSEEventStreamTypeSessionCreated

	typStr := SSESessionCreatedEventEvent(typ)
	sessionCreated.Event = typStr

	return SSEEventStream{
		SSESessionCreatedEvent: &sessionCreated,
		Type:                   typ,
	}
}

func CreateSSEEventStreamSessionDeleted(sessionDeleted SSESessionDeletedEvent) SSEEventStream {
	typ := SSEEventStreamTypeSessionDeleted

	typStr := SSESessionDeletedEventEvent(typ)
	sessionDeleted.Event = typStr

	return SSEEventStream{
		SSESessionDeletedEvent: &sessionDeleted,
		Type:                   typ,
	}
}

func CreateSSEEventStreamThinking(thinking SSEThinkingEvent) SSEEventStream {
	typ := SSEEventStreamTypeThinking

	typStr := SSEThinkingEventEvent(typ)
	thinking.Event = typStr

	return SSEEventStream{
		SSEThinkingEvent: &thinking,
		Type:             typ,
	}
}

func CreateSSEEventStreamToolExecutionComplete(toolExecutionComplete SSEToolExecutionCompleteEvent) SSEEventStream {
	typ := SSEEventStreamTypeToolExecutionComplete

	typStr := SSEToolExecutionCompleteEventEvent(typ)
	toolExecutionComplete.Event = typStr

	return SSEEventStream{
		SSEToolExecutionCompleteEvent: &toolExecutionComplete,
		Type:                          typ,
	}
}

func CreateSSEEventStreamToolExecutionStart(toolExecutionStart SSEToolExecutionStartEvent) SSEEventStream {
	typ := SSEEventStreamTypeToolExecutionStart

	typStr := SSEToolExecutionStartEventEvent(typ)
	toolExecutionStart.Event = typStr

	return SSEEventStream{
		SSEToolExecutionStartEvent: &toolExecutionStart,
		Type:                       typ,
	}
}

func CreateSSEEventStreamToolUseParameterDelta(toolUseParameterDelta SSEToolUseParameterDeltaEvent) SSEEventStream {
	typ := SSEEventStreamTypeToolUseParameterDelta

	typStr := SSEToolUseParameterDeltaEventEvent(typ)
	toolUseParameterDelta.Event = typStr

	return SSEEventStream{
		SSEToolUseParameterDeltaEvent: &toolUseParameterDelta,
		Type:                          typ,
	}
}

func CreateSSEEventStreamToolUseParameterStreamingComplete(toolUseParameterStreamingComplete SSEToolUseParameterStreamingCompleteEvent) SSEEventStream {
	typ := SSEEventStreamTypeToolUseParameterStreamingComplete

	typStr := SSEToolUseParameterStreamingCompleteEventEvent(typ)
	toolUseParameterStreamingComplete.Event = typStr

	return SSEEventStream{
		SSEToolUseParameterStreamingCompleteEvent: &toolUseParameterStreamingComplete,
		Type: typ,
	}
}

func CreateSSEEventStreamToolUseStart(toolUseStart SSEToolUseStartEvent) SSEEventStream {
	typ := SSEEventStreamTypeToolUseStart

	typStr := SSEToolUseStartEventEvent(typ)
	toolUseStart.Event = typStr

	return SSEEventStream{
		SSEToolUseStartEvent: &toolUseStart,
		Type:                 typ,
	}
}

func CreateSSEEventStreamUserMessageCreated(userMessageCreated SSEUserMessageCreatedEvent) SSEEventStream {
	typ := SSEEventStreamTypeUserMessageCreated

	typStr := SSEUserMessageCreatedEventEvent(typ)
	userMessageCreated.Event = typStr

	return SSEEventStream{
		SSEUserMessageCreatedEvent: &userMessageCreated,
		Type:                       typ,
	}
}

func (u *SSEEventStream) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Event string `json:"event"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Event {
	case "complete":
		sseCompleteEvent := new(SSECompleteEvent)
		if err := utils.UnmarshalJSON(data, &sseCompleteEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Event == complete) type SSECompleteEvent within SSEEventStream: %w", string(data), err)
		}

		u.SSECompleteEvent = sseCompleteEvent
		u.Type = SSEEventStreamTypeComplete
		return nil
	case "connected":
		sseConnectedEvent := new(SSEConnectedEvent)
		if err := utils.UnmarshalJSON(data, &sseConnectedEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Event == connected) type SSEConnectedEvent within SSEEventStream: %w", string(data), err)
		}

		u.SSEConnectedEvent = sseConnectedEvent
		u.Type = SSEEventStreamTypeConnected
		return nil
	case "content":
		sseContentEvent := new(SSEContentEvent)
		if err := utils.UnmarshalJSON(data, &sseContentEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Event == content) type SSEContentEvent within SSEEventStream: %w", string(data), err)
		}

		u.SSEContentEvent = sseContentEvent
		u.Type = SSEEventStreamTypeContent
		return nil
	case "error":
		sseErrorEvent := new(SSEErrorEvent)
		if err := utils.UnmarshalJSON(data, &sseErrorEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Event == error) type SSEErrorEvent within SSEEventStream: %w", string(data), err)
		}

		u.SSEErrorEvent = sseErrorEvent
		u.Type = SSEEventStreamTypeError
		return nil
	case "heartbeat":
		sseHeartbeatEvent := new(SSEHeartbeatEvent)
		if err := utils.UnmarshalJSON(data, &sseHeartbeatEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Event == heartbeat) type SSEHeartbeatEvent within SSEEventStream: %w", string(data), err)
		}

		u.SSEHeartbeatEvent = sseHeartbeatEvent
		u.Type = SSEEventStreamTypeHeartbeat
		return nil
	case "permission":
		ssePermissionEvent := new(SSEPermissionEvent)
		if err := utils.UnmarshalJSON(data, &ssePermissionEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Event == permission) type SSEPermissionEvent within SSEEventStream: %w", string(data), err)
		}

		u.SSEPermissionEvent = ssePermissionEvent
		u.Type = SSEEventStreamTypePermission
		return nil
	case "session_created":
		sseSessionCreatedEvent := new(SSESessionCreatedEvent)
		if err := utils.UnmarshalJSON(data, &sseSessionCreatedEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Event == session_created) type SSESessionCreatedEvent within SSEEventStream: %w", string(data), err)
		}

		u.SSESessionCreatedEvent = sseSessionCreatedEvent
		u.Type = SSEEventStreamTypeSessionCreated
		return nil
	case "session_deleted":
		sseSessionDeletedEvent := new(SSESessionDeletedEvent)
		if err := utils.UnmarshalJSON(data, &sseSessionDeletedEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Event == session_deleted) type SSESessionDeletedEvent within SSEEventStream: %w", string(data), err)
		}

		u.SSESessionDeletedEvent = sseSessionDeletedEvent
		u.Type = SSEEventStreamTypeSessionDeleted
		return nil
	case "thinking":
		sseThinkingEvent := new(SSEThinkingEvent)
		if err := utils.UnmarshalJSON(data, &sseThinkingEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Event == thinking) type SSEThinkingEvent within SSEEventStream: %w", string(data), err)
		}

		u.SSEThinkingEvent = sseThinkingEvent
		u.Type = SSEEventStreamTypeThinking
		return nil
	case "tool_execution_complete":
		sseToolExecutionCompleteEvent := new(SSEToolExecutionCompleteEvent)
		if err := utils.UnmarshalJSON(data, &sseToolExecutionCompleteEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Event == tool_execution_complete) type SSEToolExecutionCompleteEvent within SSEEventStream: %w", string(data), err)
		}

		u.SSEToolExecutionCompleteEvent = sseToolExecutionCompleteEvent
		u.Type = SSEEventStreamTypeToolExecutionComplete
		return nil
	case "tool_execution_start":
		sseToolExecutionStartEvent := new(SSEToolExecutionStartEvent)
		if err := utils.UnmarshalJSON(data, &sseToolExecutionStartEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Event == tool_execution_start) type SSEToolExecutionStartEvent within SSEEventStream: %w", string(data), err)
		}

		u.SSEToolExecutionStartEvent = sseToolExecutionStartEvent
		u.Type = SSEEventStreamTypeToolExecutionStart
		return nil
	case "tool_use_parameter_delta":
		sseToolUseParameterDeltaEvent := new(SSEToolUseParameterDeltaEvent)
		if err := utils.UnmarshalJSON(data, &sseToolUseParameterDeltaEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Event == tool_use_parameter_delta) type SSEToolUseParameterDeltaEvent within SSEEventStream: %w", string(data), err)
		}

		u.SSEToolUseParameterDeltaEvent = sseToolUseParameterDeltaEvent
		u.Type = SSEEventStreamTypeToolUseParameterDelta
		return nil
	case "tool_use_parameter_streaming_complete":
		sseToolUseParameterStreamingCompleteEvent := new(SSEToolUseParameterStreamingCompleteEvent)
		if err := utils.UnmarshalJSON(data, &sseToolUseParameterStreamingCompleteEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Event == tool_use_parameter_streaming_complete) type SSEToolUseParameterStreamingCompleteEvent within SSEEventStream: %w", string(data), err)
		}

		u.SSEToolUseParameterStreamingCompleteEvent = sseToolUseParameterStreamingCompleteEvent
		u.Type = SSEEventStreamTypeToolUseParameterStreamingComplete
		return nil
	case "tool_use_start":
		sseToolUseStartEvent := new(SSEToolUseStartEvent)
		if err := utils.UnmarshalJSON(data, &sseToolUseStartEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Event == tool_use_start) type SSEToolUseStartEvent within SSEEventStream: %w", string(data), err)
		}

		u.SSEToolUseStartEvent = sseToolUseStartEvent
		u.Type = SSEEventStreamTypeToolUseStart
		return nil
	case "user_message_created":
		sseUserMessageCreatedEvent := new(SSEUserMessageCreatedEvent)
		if err := utils.UnmarshalJSON(data, &sseUserMessageCreatedEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Event == user_message_created) type SSEUserMessageCreatedEvent within SSEEventStream: %w", string(data), err)
		}

		u.SSEUserMessageCreatedEvent = sseUserMessageCreatedEvent
		u.Type = SSEEventStreamTypeUserMessageCreated
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for SSEEventStream", string(data))
}

func (u SSEEventStream) MarshalJSON() ([]byte, error) {
	if u.SSEConnectedEvent != nil {
		return utils.MarshalJSON(u.SSEConnectedEvent, "", true)
	}

	if u.SSEHeartbeatEvent != nil {
		return utils.MarshalJSON(u.SSEHeartbeatEvent, "", true)
	}

	if u.SSEErrorEvent != nil {
		return utils.MarshalJSON(u.SSEErrorEvent, "", true)
	}

	if u.SSECompleteEvent != nil {
		return utils.MarshalJSON(u.SSECompleteEvent, "", true)
	}

	if u.SSEThinkingEvent != nil {
		return utils.MarshalJSON(u.SSEThinkingEvent, "", true)
	}

	if u.SSEContentEvent != nil {
		return utils.MarshalJSON(u.SSEContentEvent, "", true)
	}

	if u.SSEToolUseStartEvent != nil {
		return utils.MarshalJSON(u.SSEToolUseStartEvent, "", true)
	}

	if u.SSEToolUseParameterStreamingCompleteEvent != nil {
		return utils.MarshalJSON(u.SSEToolUseParameterStreamingCompleteEvent, "", true)
	}

	if u.SSEToolUseParameterDeltaEvent != nil {
		return utils.MarshalJSON(u.SSEToolUseParameterDeltaEvent, "", true)
	}

	if u.SSEToolExecutionStartEvent != nil {
		return utils.MarshalJSON(u.SSEToolExecutionStartEvent, "", true)
	}

	if u.SSEToolExecutionCompleteEvent != nil {
		return utils.MarshalJSON(u.SSEToolExecutionCompleteEvent, "", true)
	}

	if u.SSEPermissionEvent != nil {
		return utils.MarshalJSON(u.SSEPermissionEvent, "", true)
	}

	if u.SSEUserMessageCreatedEvent != nil {
		return utils.MarshalJSON(u.SSEUserMessageCreatedEvent, "", true)
	}

	if u.SSESessionCreatedEvent != nil {
		return utils.MarshalJSON(u.SSESessionCreatedEvent, "", true)
	}

	if u.SSESessionDeletedEvent != nil {
		return utils.MarshalJSON(u.SSESessionDeletedEvent, "", true)
	}

	return nil, errors.New("could not marshal union type SSEEventStream: all fields are null")
}

func (o SSEEventStream) GetEventEncoding(event string) (string, error) {
	switch event {
	case "complete":
		return "application/json", nil
	case "connected":
		return "application/json", nil
	case "content":
		return "application/json", nil
	case "error":
		return "application/json", nil
	case "heartbeat":
		return "application/json", nil
	case "permission":
		return "application/json", nil
	case "session_created":
		return "application/json", nil
	case "session_deleted":
		return "application/json", nil
	case "thinking":
		return "application/json", nil
	case "tool_execution_complete":
		return "application/json", nil
	case "tool_execution_start":
		return "application/json", nil
	case "tool_use_parameter_delta":
		return "application/json", nil
	case "tool_use_parameter_streaming_complete":
		return "application/json", nil
	case "tool_use_start":
		return "application/json", nil
	case "user_message_created":
		return "application/json", nil
	}
	return "", errors.New("could not find encoding for event: " + event)
}
