// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/recreate-run/mix-go-sdk/internal/utils"
)

type ToolNameType string

const (
	ToolNameTypeCoreToolName ToolNameType = "CoreToolName"
	ToolNameTypeStr          ToolNameType = "str"
)

// ToolName - Tool name - either a core tool or MCP tool following {serverName}_{toolName} pattern
type ToolName struct {
	CoreToolName *CoreToolName `queryParam:"inline,name=ToolName"`
	Str          *string       `queryParam:"inline,name=ToolName"`

	Type ToolNameType
}

func CreateToolNameCoreToolName(coreToolName CoreToolName) ToolName {
	typ := ToolNameTypeCoreToolName

	return ToolName{
		CoreToolName: &coreToolName,
		Type:         typ,
	}
}

func CreateToolNameStr(str string) ToolName {
	typ := ToolNameTypeStr

	return ToolName{
		Str:  &str,
		Type: typ,
	}
}

func (u *ToolName) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var coreToolName CoreToolName = CoreToolName("")
	if err := utils.UnmarshalJSON(data, &coreToolName, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ToolNameTypeCoreToolName,
			Value: &coreToolName,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ToolNameTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ToolName", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestCandidate(candidates)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ToolName", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ToolNameType)
	switch best.Type {
	case ToolNameTypeCoreToolName:
		u.CoreToolName = best.Value.(*CoreToolName)
		return nil
	case ToolNameTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ToolName", string(data))
}

func (u ToolName) MarshalJSON() ([]byte, error) {
	if u.CoreToolName != nil {
		return utils.MarshalJSON(u.CoreToolName, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type ToolName: all fields are null")
}
