// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/recreate-run/mix-go-sdk/internal/utils"
)

type ToolNameType string

const (
	ToolNameTypeCoreToolName ToolNameType = "CoreToolName"
	ToolNameTypeStr          ToolNameType = "str"
)

// ToolName - Tool name - either a core tool or MCP tool following {serverName}_{toolName} pattern
type ToolName struct {
	CoreToolName *CoreToolName `queryParam:"inline" union:"member"`
	Str          *string       `queryParam:"inline" union:"member"`

	Type ToolNameType
}

func CreateToolNameCoreToolName(coreToolName CoreToolName) ToolName {
	typ := ToolNameTypeCoreToolName

	return ToolName{
		CoreToolName: &coreToolName,
		Type:         typ,
	}
}

func CreateToolNameStr(str string) ToolName {
	typ := ToolNameTypeStr

	return ToolName{
		Str:  &str,
		Type: typ,
	}
}

func (u *ToolName) UnmarshalJSON(data []byte) error {

	var coreToolName CoreToolName = CoreToolName("")
	if err := utils.UnmarshalJSON(data, &coreToolName, "", true, nil); err == nil {
		u.CoreToolName = &coreToolName
		u.Type = ToolNameTypeCoreToolName
		return nil
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = ToolNameTypeStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ToolName", string(data))
}

func (u ToolName) MarshalJSON() ([]byte, error) {
	if u.CoreToolName != nil {
		return utils.MarshalJSON(u.CoreToolName, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type ToolName: all fields are null")
}
