// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ToolCallData struct {
	// Whether tool call has finished
	Finished bool `json:"finished"`
	// Unique tool call identifier
	ID string `json:"id"`
	// Tool input parameters
	Input string `json:"input"`
	// Whether tool call resulted in error (optional)
	IsError *bool `json:"isError,omitempty"`
	// Tool name - either a core tool or MCP tool following {serverName}_{toolName} pattern
	Name ToolName `json:"name"`
	// Tool execution result (optional)
	Result *string `json:"result,omitempty"`
	// Tool type
	Type string `json:"type"`
}

func (t *ToolCallData) GetFinished() bool {
	if t == nil {
		return false
	}
	return t.Finished
}

func (t *ToolCallData) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *ToolCallData) GetInput() string {
	if t == nil {
		return ""
	}
	return t.Input
}

func (t *ToolCallData) GetIsError() *bool {
	if t == nil {
		return nil
	}
	return t.IsError
}

func (t *ToolCallData) GetName() ToolName {
	if t == nil {
		return ToolName{}
	}
	return t.Name
}

func (t *ToolCallData) GetResult() *string {
	if t == nil {
		return nil
	}
	return t.Result
}

func (t *ToolCallData) GetType() string {
	if t == nil {
		return ""
	}
	return t.Type
}
