// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/recreate-run/mix-go-sdk/models/components"
)

type ErrorResponse struct {
	Error_   components.RESTError    `json:"error"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ErrorResponse{}

func (e *ErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
