// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package config

import (
	"github.com/recreate-run/mix-go-sdk/retry"
	"net/http"
	"time"
)

type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

type SDKConfiguration struct {
	Client HTTPClient

	ServerURL   string
	UserAgent   string
	RetryConfig *retry.Config
	Timeout     *time.Duration
}

func (c *SDKConfiguration) GetServerDetails() (string, map[string]string) {
	return c.ServerURL, map[string]string{}
}
